// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: core.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO core.events (
    id, project_id, task_id, run_id, event_type, aggregate_type, aggregate_id,
    aggregate_version, payload, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, project_id, task_id, run_id, event_type, aggregate_type, aggregate_id,
    aggregate_version, payload, created_at
`

type AppendEventParams struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	TaskID           pgtype.UUID
	RunID            pgtype.UUID
	EventType        string
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	Payload          []byte
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (CoreEvent, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.ID,
		arg.ProjectID,
		arg.TaskID,
		arg.RunID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.Payload,
		arg.CreatedAt,
	)
	var i CoreEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactBySHA256 = `-- name: GetArtifactBySHA256 :one
SELECT id, sha256, size_bytes, media_type, logical_kind, storage_path, compression, created_at
FROM core.artifacts
WHERE sha256 = $1
`

func (q *Queries) GetArtifactBySHA256(ctx context.Context, sha256 string) (CoreArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactBySHA256, sha256)
	var i CoreArtifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.MediaType,
		&i.LogicalKind,
		&i.StoragePath,
		&i.Compression,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, project_id, task_id, run_id, event_type, aggregate_type, aggregate_id,
    aggregate_version, payload, created_at
FROM core.events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (CoreEvent, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i CoreEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO core.artifacts (
    id, sha256, size_bytes, media_type, logical_kind, storage_path, compression, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, sha256, size_bytes, media_type, logical_kind, storage_path, compression, created_at
`

type InsertArtifactParams struct {
	ID          pgtype.UUID
	Sha256      string
	SizeBytes   int64
	MediaType   string
	LogicalKind string
	StoragePath string
	Compression pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (CoreArtifact, error) {
	row := q.db.QueryRow(ctx, insertArtifact,
		arg.ID,
		arg.Sha256,
		arg.SizeBytes,
		arg.MediaType,
		arg.LogicalKind,
		arg.StoragePath,
		arg.Compression,
		arg.CreatedAt,
	)
	var i CoreArtifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.MediaType,
		&i.LogicalKind,
		&i.StoragePath,
		&i.Compression,
		&i.CreatedAt,
	)
	return i, err
}
