// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: core.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireGlobalExecutionLease = `-- name: AcquireGlobalExecutionLease :one
UPDATE core.execution_leases
SET run_id = $1,
    coordinator_identity = $2,
    acquired_at = $3,
    aggregate_version = aggregate_version + 1
WHERE lease_name = 'global-source-mutation-v1'
  AND run_id IS NULL
  AND aggregate_version = $4
RETURNING lease_name, run_id, coordinator_identity, acquired_at, aggregate_version
`

type AcquireGlobalExecutionLeaseParams struct {
	RunID                    pgtype.UUID
	CoordinatorIdentity      pgtype.Text
	AcquiredAt               pgtype.Timestamptz
	ExpectedAggregateVersion int64
}

func (q *Queries) AcquireGlobalExecutionLease(ctx context.Context, arg AcquireGlobalExecutionLeaseParams) (CoreExecutionLease, error) {
	row := q.db.QueryRow(ctx, acquireGlobalExecutionLease,
		arg.RunID,
		arg.CoordinatorIdentity,
		arg.AcquiredAt,
		arg.ExpectedAggregateVersion,
	)
	var i CoreExecutionLease
	err := row.Scan(
		&i.LeaseName,
		&i.RunID,
		&i.CoordinatorIdentity,
		&i.AcquiredAt,
		&i.AggregateVersion,
	)
	return i, err
}

const admitSchedulerTask = `-- name: AdmitSchedulerTask :one
UPDATE core.tasks
SET status = 'admitted',
    aggregate_version = aggregate_version + 1,
    updated_at = $1
WHERE project_id = $2
  AND id = $3
  AND status = 'pending'
  AND accepted_version_id = $4
  AND aggregate_version = $5
RETURNING id, project_id, external_task_id, status, accepted_version_id,
    created_at, updated_at, aggregate_version
`

type AdmitSchedulerTaskParams struct {
	UpdatedAt                pgtype.Timestamptz
	ProjectID                pgtype.UUID
	TaskID                   pgtype.UUID
	TaskVersionID            pgtype.UUID
	ExpectedAggregateVersion int64
}

func (q *Queries) AdmitSchedulerTask(ctx context.Context, arg AdmitSchedulerTaskParams) (CoreTask, error) {
	row := q.db.QueryRow(ctx, admitSchedulerTask,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.TaskID,
		arg.TaskVersionID,
		arg.ExpectedAggregateVersion,
	)
	var i CoreTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalTaskID,
		&i.Status,
		&i.AcceptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AggregateVersion,
	)
	return i, err
}

const appendEvent = `-- name: AppendEvent :one
INSERT INTO core.events (
    id, project_id, task_id, run_id, event_type, aggregate_type, aggregate_id,
    aggregate_version, payload, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, project_id, task_id, run_id, event_type, aggregate_type, aggregate_id,
    aggregate_version, payload, created_at
`

type AppendEventParams struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	TaskID           pgtype.UUID
	RunID            pgtype.UUID
	EventType        string
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	Payload          []byte
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (CoreEvent, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.ID,
		arg.ProjectID,
		arg.TaskID,
		arg.RunID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.Payload,
		arg.CreatedAt,
	)
	var i CoreEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const approveTaskVersion = `-- name: ApproveTaskVersion :one
UPDATE core.tasks AS t
SET accepted_version_id = $1,
    status = 'pending',
    aggregate_version = aggregate_version + 1,
    updated_at = $2
WHERE t.project_id = $3
  AND t.id = $4
  AND t.status = 'awaiting_approval'
  AND t.aggregate_version = $5
  AND t.accepted_version_id IS NULL
  AND EXISTS (
      SELECT 1
      FROM core.task_versions AS tv
      WHERE tv.id = $1 AND tv.task_id = t.id
  )
RETURNING t.id, t.project_id, t.external_task_id, t.status, t.accepted_version_id,
    t.created_at, t.updated_at, t.aggregate_version
`

type ApproveTaskVersionParams struct {
	TaskVersionID            pgtype.UUID
	UpdatedAt                pgtype.Timestamptz
	ProjectID                pgtype.UUID
	TaskID                   pgtype.UUID
	ExpectedAggregateVersion int64
}

func (q *Queries) ApproveTaskVersion(ctx context.Context, arg ApproveTaskVersionParams) (CoreTask, error) {
	row := q.db.QueryRow(ctx, approveTaskVersion,
		arg.TaskVersionID,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.TaskID,
		arg.ExpectedAggregateVersion,
	)
	var i CoreTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalTaskID,
		&i.Status,
		&i.AcceptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AggregateVersion,
	)
	return i, err
}

const compareAndUpdateTaskState = `-- name: CompareAndUpdateTaskState :one
UPDATE core.tasks
SET status = $1,
    aggregate_version = aggregate_version + 1,
    updated_at = $2
WHERE project_id = $3
  AND id = $4
  AND status = $5
  AND aggregate_version = $6
RETURNING id, project_id, external_task_id, status, accepted_version_id,
    created_at, updated_at, aggregate_version
`

type CompareAndUpdateTaskStateParams struct {
	NewStatus                string
	UpdatedAt                pgtype.Timestamptz
	ProjectID                pgtype.UUID
	TaskID                   pgtype.UUID
	ExpectedStatus           string
	ExpectedAggregateVersion int64
}

func (q *Queries) CompareAndUpdateTaskState(ctx context.Context, arg CompareAndUpdateTaskStateParams) (CoreTask, error) {
	row := q.db.QueryRow(ctx, compareAndUpdateTaskState,
		arg.NewStatus,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.TaskID,
		arg.ExpectedStatus,
		arg.ExpectedAggregateVersion,
	)
	var i CoreTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalTaskID,
		&i.Status,
		&i.AcceptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AggregateVersion,
	)
	return i, err
}

const countRunAdmissionEvents = `-- name: CountRunAdmissionEvents :one
SELECT count(*)
FROM core.events
WHERE run_id = $1
  AND (
      (event_type = 'run.admitted' AND aggregate_type = 'run'
       AND aggregate_id = $1 AND aggregate_version = 1)
      OR
      (event_type = 'task.admitted' AND aggregate_type = 'task'
       AND aggregate_id = $2
       AND aggregate_version = $3)
  )
`

type CountRunAdmissionEventsParams struct {
	RunID                pgtype.UUID
	TaskID               pgtype.UUID
	TaskAggregateVersion int64
}

func (q *Queries) CountRunAdmissionEvents(ctx context.Context, arg CountRunAdmissionEventsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRunAdmissionEvents, arg.RunID, arg.TaskID, arg.TaskAggregateVersion)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getApprovedTaskWithSelectedVersion = `-- name: GetApprovedTaskWithSelectedVersion :one
SELECT
    t.id, t.project_id, t.external_task_id, t.status, t.accepted_version_id,
    t.created_at, t.updated_at, t.aggregate_version,
    tv.id AS selected_version_id,
    tv.version_number AS selected_version_number,
    tv.source_artifact_id AS selected_source_artifact_id,
    tv.title AS selected_title,
    tv.goal AS selected_goal,
    tv.risk_class AS selected_risk_class,
    tv.mutation_class AS selected_mutation_class,
    tv.network_profile AS selected_network_profile,
    tv.priority AS selected_priority,
    tv.read_only_investigation AS selected_read_only_investigation,
    tv.scope AS selected_scope,
    tv.excluded_scope AS selected_excluded_scope,
    tv.verification_plan AS selected_verification_plan,
    tv.budget AS selected_budget,
    tv.secret_requirements AS selected_secret_requirements,
    tv.expected_paths AS selected_expected_paths,
    tv.operator_checkpoints AS selected_operator_checkpoints,
    tv.created_at AS selected_created_at
FROM core.tasks AS t
JOIN core.task_versions AS tv ON tv.id = t.accepted_version_id AND tv.task_id = t.id
WHERE t.project_id = $1 AND t.id = $2
`

type GetApprovedTaskWithSelectedVersionParams struct {
	ProjectID pgtype.UUID
	TaskID    pgtype.UUID
}

type GetApprovedTaskWithSelectedVersionRow struct {
	ID                            pgtype.UUID
	ProjectID                     pgtype.UUID
	ExternalTaskID                string
	Status                        string
	AcceptedVersionID             pgtype.UUID
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	AggregateVersion              int64
	SelectedVersionID             pgtype.UUID
	SelectedVersionNumber         int32
	SelectedSourceArtifactID      pgtype.UUID
	SelectedTitle                 string
	SelectedGoal                  string
	SelectedRiskClass             string
	SelectedMutationClass         string
	SelectedNetworkProfile        string
	SelectedPriority              int32
	SelectedReadOnlyInvestigation bool
	SelectedScope                 []byte
	SelectedExcludedScope         []byte
	SelectedVerificationPlan      []byte
	SelectedBudget                []byte
	SelectedSecretRequirements    []byte
	SelectedExpectedPaths         []byte
	SelectedOperatorCheckpoints   []byte
	SelectedCreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetApprovedTaskWithSelectedVersion(ctx context.Context, arg GetApprovedTaskWithSelectedVersionParams) (GetApprovedTaskWithSelectedVersionRow, error) {
	row := q.db.QueryRow(ctx, getApprovedTaskWithSelectedVersion, arg.ProjectID, arg.TaskID)
	var i GetApprovedTaskWithSelectedVersionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalTaskID,
		&i.Status,
		&i.AcceptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AggregateVersion,
		&i.SelectedVersionID,
		&i.SelectedVersionNumber,
		&i.SelectedSourceArtifactID,
		&i.SelectedTitle,
		&i.SelectedGoal,
		&i.SelectedRiskClass,
		&i.SelectedMutationClass,
		&i.SelectedNetworkProfile,
		&i.SelectedPriority,
		&i.SelectedReadOnlyInvestigation,
		&i.SelectedScope,
		&i.SelectedExcludedScope,
		&i.SelectedVerificationPlan,
		&i.SelectedBudget,
		&i.SelectedSecretRequirements,
		&i.SelectedExpectedPaths,
		&i.SelectedOperatorCheckpoints,
		&i.SelectedCreatedAt,
	)
	return i, err
}

const getArtifactBySHA256 = `-- name: GetArtifactBySHA256 :one
SELECT id, sha256, size_bytes, media_type, logical_kind, storage_path, compression, created_at
FROM core.artifacts
WHERE sha256 = $1
`

func (q *Queries) GetArtifactBySHA256(ctx context.Context, sha256 string) (CoreArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactBySHA256, sha256)
	var i CoreArtifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.MediaType,
		&i.LogicalKind,
		&i.StoragePath,
		&i.Compression,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, project_id, task_id, run_id, event_type, aggregate_type, aggregate_id,
    aggregate_version, payload, created_at
FROM core.events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (CoreEvent, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i CoreEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getGlobalExecutionLease = `-- name: GetGlobalExecutionLease :one
SELECT lease_name, run_id, coordinator_identity, acquired_at, aggregate_version
FROM core.execution_leases
WHERE lease_name = 'global-source-mutation-v1'
`

func (q *Queries) GetGlobalExecutionLease(ctx context.Context) (CoreExecutionLease, error) {
	row := q.db.QueryRow(ctx, getGlobalExecutionLease)
	var i CoreExecutionLease
	err := row.Scan(
		&i.LeaseName,
		&i.RunID,
		&i.CoordinatorIdentity,
		&i.AcquiredAt,
		&i.AggregateVersion,
	)
	return i, err
}

const getGlobalExecutionLeaseForUpdate = `-- name: GetGlobalExecutionLeaseForUpdate :one
SELECT lease_name, run_id, coordinator_identity, acquired_at, aggregate_version
FROM core.execution_leases
WHERE lease_name = 'global-source-mutation-v1'
FOR UPDATE
`

func (q *Queries) GetGlobalExecutionLeaseForUpdate(ctx context.Context) (CoreExecutionLease, error) {
	row := q.db.QueryRow(ctx, getGlobalExecutionLeaseForUpdate)
	var i CoreExecutionLease
	err := row.Scan(
		&i.LeaseName,
		&i.RunID,
		&i.CoordinatorIdentity,
		&i.AcquiredAt,
		&i.AggregateVersion,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, name, status, created_at, updated_at
FROM core.projects
WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id pgtype.UUID) (CoreProject, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i CoreProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectRegistrationByCanonicalSourcePath = `-- name: GetProjectRegistrationByCanonicalSourcePath :one
SELECT
    p.id AS project_id,
    p.name,
    p.status,
    p.created_at,
    p.updated_at,
    ps.id AS project_source_id,
    ps.canonical_source_path,
    ps.managed_repository_path,
    ps.current_commit,
    ps.current_tree,
    ps.current_branch,
    ps.default_branch,
    ps.dirty_state,
    ps.remotes
FROM core.projects AS p
JOIN core.project_sources AS ps ON ps.project_id = p.id
WHERE ps.canonical_source_path = $1
`

type GetProjectRegistrationByCanonicalSourcePathRow struct {
	ProjectID             pgtype.UUID
	Name                  string
	Status                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ProjectSourceID       pgtype.UUID
	CanonicalSourcePath   string
	ManagedRepositoryPath string
	CurrentCommit         string
	CurrentTree           string
	CurrentBranch         pgtype.Text
	DefaultBranch         pgtype.Text
	DirtyState            []byte
	Remotes               []byte
}

func (q *Queries) GetProjectRegistrationByCanonicalSourcePath(ctx context.Context, canonicalSourcePath string) (GetProjectRegistrationByCanonicalSourcePathRow, error) {
	row := q.db.QueryRow(ctx, getProjectRegistrationByCanonicalSourcePath, canonicalSourcePath)
	var i GetProjectRegistrationByCanonicalSourcePathRow
	err := row.Scan(
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectSourceID,
		&i.CanonicalSourcePath,
		&i.ManagedRepositoryPath,
		&i.CurrentCommit,
		&i.CurrentTree,
		&i.CurrentBranch,
		&i.DefaultBranch,
		&i.DirtyState,
		&i.Remotes,
	)
	return i, err
}

const getRun = `-- name: GetRun :one
SELECT id, project_id, task_id, task_version_id, project_source_id, status,
    aggregate_version, admitted_task_aggregate_version, source_commit,
    source_tree, coordinator_identity, created_at, updated_at, released_at
FROM core.runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id pgtype.UUID) (CoreRun, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i CoreRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.TaskVersionID,
		&i.ProjectSourceID,
		&i.Status,
		&i.AggregateVersion,
		&i.AdmittedTaskAggregateVersion,
		&i.SourceCommit,
		&i.SourceTree,
		&i.CoordinatorIdentity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const getSchedulerProjectSource = `-- name: GetSchedulerProjectSource :one
SELECT id, project_id, current_commit, current_tree
FROM core.project_sources
WHERE id = $1 AND project_id = $2
`

type GetSchedulerProjectSourceParams struct {
	ProjectSourceID pgtype.UUID
	ProjectID       pgtype.UUID
}

type GetSchedulerProjectSourceRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	CurrentCommit string
	CurrentTree   string
}

func (q *Queries) GetSchedulerProjectSource(ctx context.Context, arg GetSchedulerProjectSourceParams) (GetSchedulerProjectSourceRow, error) {
	row := q.db.QueryRow(ctx, getSchedulerProjectSource, arg.ProjectSourceID, arg.ProjectID)
	var i GetSchedulerProjectSourceRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CurrentCommit,
		&i.CurrentTree,
	)
	return i, err
}

const getTaskAndVersion = `-- name: GetTaskAndVersion :one
SELECT
    t.id, t.project_id, t.external_task_id, t.status, t.accepted_version_id,
    t.created_at, t.updated_at, t.aggregate_version,
    tv.id AS task_version_id,
    tv.version_number AS task_version_number,
    tv.source_artifact_id AS task_version_source_artifact_id,
    tv.title AS task_version_title,
    tv.goal AS task_version_goal,
    tv.risk_class AS task_version_risk_class,
    tv.mutation_class AS task_version_mutation_class,
    tv.network_profile AS task_version_network_profile,
    tv.priority AS task_version_priority,
    tv.read_only_investigation AS task_version_read_only_investigation,
    tv.scope AS task_version_scope,
    tv.excluded_scope AS task_version_excluded_scope,
    tv.verification_plan AS task_version_verification_plan,
    tv.budget AS task_version_budget,
    tv.secret_requirements AS task_version_secret_requirements,
    tv.expected_paths AS task_version_expected_paths,
    tv.operator_checkpoints AS task_version_operator_checkpoints,
    tv.created_at AS task_version_created_at
FROM core.tasks AS t
JOIN core.task_versions AS tv ON tv.task_id = t.id
WHERE t.project_id = $1
  AND t.id = $2
  AND tv.id = $3
`

type GetTaskAndVersionParams struct {
	ProjectID     pgtype.UUID
	TaskID        pgtype.UUID
	TaskVersionID pgtype.UUID
}

type GetTaskAndVersionRow struct {
	ID                               pgtype.UUID
	ProjectID                        pgtype.UUID
	ExternalTaskID                   string
	Status                           string
	AcceptedVersionID                pgtype.UUID
	CreatedAt                        pgtype.Timestamptz
	UpdatedAt                        pgtype.Timestamptz
	AggregateVersion                 int64
	TaskVersionID                    pgtype.UUID
	TaskVersionNumber                int32
	TaskVersionSourceArtifactID      pgtype.UUID
	TaskVersionTitle                 string
	TaskVersionGoal                  string
	TaskVersionRiskClass             string
	TaskVersionMutationClass         string
	TaskVersionNetworkProfile        string
	TaskVersionPriority              int32
	TaskVersionReadOnlyInvestigation bool
	TaskVersionScope                 []byte
	TaskVersionExcludedScope         []byte
	TaskVersionVerificationPlan      []byte
	TaskVersionBudget                []byte
	TaskVersionSecretRequirements    []byte
	TaskVersionExpectedPaths         []byte
	TaskVersionOperatorCheckpoints   []byte
	TaskVersionCreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetTaskAndVersion(ctx context.Context, arg GetTaskAndVersionParams) (GetTaskAndVersionRow, error) {
	row := q.db.QueryRow(ctx, getTaskAndVersion, arg.ProjectID, arg.TaskID, arg.TaskVersionID)
	var i GetTaskAndVersionRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalTaskID,
		&i.Status,
		&i.AcceptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AggregateVersion,
		&i.TaskVersionID,
		&i.TaskVersionNumber,
		&i.TaskVersionSourceArtifactID,
		&i.TaskVersionTitle,
		&i.TaskVersionGoal,
		&i.TaskVersionRiskClass,
		&i.TaskVersionMutationClass,
		&i.TaskVersionNetworkProfile,
		&i.TaskVersionPriority,
		&i.TaskVersionReadOnlyInvestigation,
		&i.TaskVersionScope,
		&i.TaskVersionExcludedScope,
		&i.TaskVersionVerificationPlan,
		&i.TaskVersionBudget,
		&i.TaskVersionSecretRequirements,
		&i.TaskVersionExpectedPaths,
		&i.TaskVersionOperatorCheckpoints,
		&i.TaskVersionCreatedAt,
	)
	return i, err
}

const getTaskImport = `-- name: GetTaskImport :one
SELECT id, project_id, source_artifact_id, task_id, source_name, source_sha256,
    media_type, status, created_at, updated_at
FROM core.task_imports
WHERE id = $1
`

func (q *Queries) GetTaskImport(ctx context.Context, id pgtype.UUID) (CoreTaskImport, error) {
	row := q.db.QueryRow(ctx, getTaskImport, id)
	var i CoreTaskImport
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceArtifactID,
		&i.TaskID,
		&i.SourceName,
		&i.SourceSha256,
		&i.MediaType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskImportBySourceIdentity = `-- name: GetTaskImportBySourceIdentity :one
SELECT
    ti.id, ti.project_id, ti.source_artifact_id, ti.task_id, ti.source_name,
    ti.source_sha256, ti.media_type, ti.status, ti.created_at, ti.updated_at,
    a.size_bytes AS artifact_size_bytes,
    a.storage_path AS artifact_storage_path
FROM core.task_imports AS ti
JOIN core.artifacts AS a ON a.id = ti.source_artifact_id
WHERE ti.project_id = $1 AND ti.source_name = $2
`

type GetTaskImportBySourceIdentityParams struct {
	ProjectID  pgtype.UUID
	SourceName string
}

type GetTaskImportBySourceIdentityRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	SourceArtifactID    pgtype.UUID
	TaskID              pgtype.UUID
	SourceName          string
	SourceSha256        string
	MediaType           string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	ArtifactSizeBytes   int64
	ArtifactStoragePath string
}

func (q *Queries) GetTaskImportBySourceIdentity(ctx context.Context, arg GetTaskImportBySourceIdentityParams) (GetTaskImportBySourceIdentityRow, error) {
	row := q.db.QueryRow(ctx, getTaskImportBySourceIdentity, arg.ProjectID, arg.SourceName)
	var i GetTaskImportBySourceIdentityRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceArtifactID,
		&i.TaskID,
		&i.SourceName,
		&i.SourceSha256,
		&i.MediaType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArtifactSizeBytes,
		&i.ArtifactStoragePath,
	)
	return i, err
}

const getTaskWithSelectedVersionByExternalID = `-- name: GetTaskWithSelectedVersionByExternalID :one
SELECT
    t.id, t.project_id, t.external_task_id, t.status, t.accepted_version_id,
    t.created_at, t.updated_at, t.aggregate_version,
    tv.id AS selected_version_id,
    tv.version_number AS selected_version_number,
    tv.source_artifact_id AS selected_source_artifact_id,
    tv.title AS selected_title,
    tv.goal AS selected_goal,
    tv.risk_class AS selected_risk_class,
    tv.mutation_class AS selected_mutation_class,
    tv.network_profile AS selected_network_profile,
    tv.priority AS selected_priority,
    tv.read_only_investigation AS selected_read_only_investigation,
    tv.scope AS selected_scope,
    tv.excluded_scope AS selected_excluded_scope,
    tv.verification_plan AS selected_verification_plan,
    tv.budget AS selected_budget,
    tv.secret_requirements AS selected_secret_requirements,
    tv.expected_paths AS selected_expected_paths,
    tv.operator_checkpoints AS selected_operator_checkpoints,
    tv.created_at AS selected_created_at
FROM core.tasks AS t
LEFT JOIN core.task_versions AS tv ON tv.id = t.accepted_version_id
WHERE t.project_id = $1 AND t.external_task_id = $2
`

type GetTaskWithSelectedVersionByExternalIDParams struct {
	ProjectID      pgtype.UUID
	ExternalTaskID string
}

type GetTaskWithSelectedVersionByExternalIDRow struct {
	ID                            pgtype.UUID
	ProjectID                     pgtype.UUID
	ExternalTaskID                string
	Status                        string
	AcceptedVersionID             pgtype.UUID
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	AggregateVersion              int64
	SelectedVersionID             pgtype.UUID
	SelectedVersionNumber         pgtype.Int4
	SelectedSourceArtifactID      pgtype.UUID
	SelectedTitle                 pgtype.Text
	SelectedGoal                  pgtype.Text
	SelectedRiskClass             pgtype.Text
	SelectedMutationClass         pgtype.Text
	SelectedNetworkProfile        pgtype.Text
	SelectedPriority              pgtype.Int4
	SelectedReadOnlyInvestigation pgtype.Bool
	SelectedScope                 []byte
	SelectedExcludedScope         []byte
	SelectedVerificationPlan      []byte
	SelectedBudget                []byte
	SelectedSecretRequirements    []byte
	SelectedExpectedPaths         []byte
	SelectedOperatorCheckpoints   []byte
	SelectedCreatedAt             pgtype.Timestamptz
}

func (q *Queries) GetTaskWithSelectedVersionByExternalID(ctx context.Context, arg GetTaskWithSelectedVersionByExternalIDParams) (GetTaskWithSelectedVersionByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskWithSelectedVersionByExternalID, arg.ProjectID, arg.ExternalTaskID)
	var i GetTaskWithSelectedVersionByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalTaskID,
		&i.Status,
		&i.AcceptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AggregateVersion,
		&i.SelectedVersionID,
		&i.SelectedVersionNumber,
		&i.SelectedSourceArtifactID,
		&i.SelectedTitle,
		&i.SelectedGoal,
		&i.SelectedRiskClass,
		&i.SelectedMutationClass,
		&i.SelectedNetworkProfile,
		&i.SelectedPriority,
		&i.SelectedReadOnlyInvestigation,
		&i.SelectedScope,
		&i.SelectedExcludedScope,
		&i.SelectedVerificationPlan,
		&i.SelectedBudget,
		&i.SelectedSecretRequirements,
		&i.SelectedExpectedPaths,
		&i.SelectedOperatorCheckpoints,
		&i.SelectedCreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO core.artifacts (
    id, sha256, size_bytes, media_type, logical_kind, storage_path, compression, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, sha256, size_bytes, media_type, logical_kind, storage_path, compression, created_at
`

type InsertArtifactParams struct {
	ID          pgtype.UUID
	Sha256      string
	SizeBytes   int64
	MediaType   string
	LogicalKind string
	StoragePath string
	Compression pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (CoreArtifact, error) {
	row := q.db.QueryRow(ctx, insertArtifact,
		arg.ID,
		arg.Sha256,
		arg.SizeBytes,
		arg.MediaType,
		arg.LogicalKind,
		arg.StoragePath,
		arg.Compression,
		arg.CreatedAt,
	)
	var i CoreArtifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.MediaType,
		&i.LogicalKind,
		&i.StoragePath,
		&i.Compression,
		&i.CreatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO core.projects (
    id, name, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, status, created_at, updated_at
`

type InsertProjectParams struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (CoreProject, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProjectSource = `-- name: InsertProjectSource :one
INSERT INTO core.project_sources (
    id, project_id, canonical_source_path, managed_repository_path,
    current_commit, current_tree, current_branch, default_branch,
    dirty_state, remotes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, project_id, canonical_source_path, managed_repository_path,
    current_commit, current_tree, current_branch, default_branch,
    dirty_state, remotes
`

type InsertProjectSourceParams struct {
	ID                    pgtype.UUID
	ProjectID             pgtype.UUID
	CanonicalSourcePath   string
	ManagedRepositoryPath string
	CurrentCommit         string
	CurrentTree           string
	CurrentBranch         pgtype.Text
	DefaultBranch         pgtype.Text
	DirtyState            []byte
	Remotes               []byte
}

func (q *Queries) InsertProjectSource(ctx context.Context, arg InsertProjectSourceParams) (CoreProjectSource, error) {
	row := q.db.QueryRow(ctx, insertProjectSource,
		arg.ID,
		arg.ProjectID,
		arg.CanonicalSourcePath,
		arg.ManagedRepositoryPath,
		arg.CurrentCommit,
		arg.CurrentTree,
		arg.CurrentBranch,
		arg.DefaultBranch,
		arg.DirtyState,
		arg.Remotes,
	)
	var i CoreProjectSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CanonicalSourcePath,
		&i.ManagedRepositoryPath,
		&i.CurrentCommit,
		&i.CurrentTree,
		&i.CurrentBranch,
		&i.DefaultBranch,
		&i.DirtyState,
		&i.Remotes,
	)
	return i, err
}

const insertRun = `-- name: InsertRun :one
INSERT INTO core.runs (
    id, project_id, task_id, task_version_id, project_source_id, status,
    admitted_task_aggregate_version, source_commit, source_tree,
    coordinator_identity, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, 'active', $6, $7, $8, $9, $10, $10
)
RETURNING id, project_id, task_id, task_version_id, project_source_id, status,
    aggregate_version, admitted_task_aggregate_version, source_commit,
    source_tree, coordinator_identity, created_at, updated_at, released_at
`

type InsertRunParams struct {
	ID                           pgtype.UUID
	ProjectID                    pgtype.UUID
	TaskID                       pgtype.UUID
	TaskVersionID                pgtype.UUID
	ProjectSourceID              pgtype.UUID
	AdmittedTaskAggregateVersion int64
	SourceCommit                 string
	SourceTree                   string
	CoordinatorIdentity          string
	CreatedAt                    pgtype.Timestamptz
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) (CoreRun, error) {
	row := q.db.QueryRow(ctx, insertRun,
		arg.ID,
		arg.ProjectID,
		arg.TaskID,
		arg.TaskVersionID,
		arg.ProjectSourceID,
		arg.AdmittedTaskAggregateVersion,
		arg.SourceCommit,
		arg.SourceTree,
		arg.CoordinatorIdentity,
		arg.CreatedAt,
	)
	var i CoreRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.TaskVersionID,
		&i.ProjectSourceID,
		&i.Status,
		&i.AggregateVersion,
		&i.AdmittedTaskAggregateVersion,
		&i.SourceCommit,
		&i.SourceTree,
		&i.CoordinatorIdentity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO core.tasks (
    id, project_id, external_task_id, status, accepted_version_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, project_id, external_task_id, status, accepted_version_id, created_at, updated_at,
    aggregate_version
`

type InsertTaskParams struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	ExternalTaskID    string
	Status            string
	AcceptedVersionID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (CoreTask, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.ID,
		arg.ProjectID,
		arg.ExternalTaskID,
		arg.Status,
		arg.AcceptedVersionID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreTask
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ExternalTaskID,
		&i.Status,
		&i.AcceptedVersionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AggregateVersion,
	)
	return i, err
}

const insertTaskAcceptanceCriterion = `-- name: InsertTaskAcceptanceCriterion :one
INSERT INTO core.task_acceptance_criteria (
    id, task_id, external_criterion_id, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, task_id, external_criterion_id, status, created_at, updated_at
`

type InsertTaskAcceptanceCriterionParams struct {
	ID                  pgtype.UUID
	TaskID              pgtype.UUID
	ExternalCriterionID string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) InsertTaskAcceptanceCriterion(ctx context.Context, arg InsertTaskAcceptanceCriterionParams) (CoreTaskAcceptanceCriterium, error) {
	row := q.db.QueryRow(ctx, insertTaskAcceptanceCriterion,
		arg.ID,
		arg.TaskID,
		arg.ExternalCriterionID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreTaskAcceptanceCriterium
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ExternalCriterionID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTaskAcceptanceVersion = `-- name: InsertTaskAcceptanceVersion :one
INSERT INTO core.task_acceptance_versions (
    id, criterion_id, task_id, task_version_id, version_number, requirement,
    verification_method, verification_reference, operator_checkpoint, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, criterion_id, task_id, task_version_id, version_number, requirement,
    verification_method, verification_reference, operator_checkpoint, created_at
`

type InsertTaskAcceptanceVersionParams struct {
	ID                    pgtype.UUID
	CriterionID           pgtype.UUID
	TaskID                pgtype.UUID
	TaskVersionID         pgtype.UUID
	VersionNumber         int32
	Requirement           string
	VerificationMethod    string
	VerificationReference pgtype.Text
	OperatorCheckpoint    []byte
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertTaskAcceptanceVersion(ctx context.Context, arg InsertTaskAcceptanceVersionParams) (CoreTaskAcceptanceVersion, error) {
	row := q.db.QueryRow(ctx, insertTaskAcceptanceVersion,
		arg.ID,
		arg.CriterionID,
		arg.TaskID,
		arg.TaskVersionID,
		arg.VersionNumber,
		arg.Requirement,
		arg.VerificationMethod,
		arg.VerificationReference,
		arg.OperatorCheckpoint,
		arg.CreatedAt,
	)
	var i CoreTaskAcceptanceVersion
	err := row.Scan(
		&i.ID,
		&i.CriterionID,
		&i.TaskID,
		&i.TaskVersionID,
		&i.VersionNumber,
		&i.Requirement,
		&i.VerificationMethod,
		&i.VerificationReference,
		&i.OperatorCheckpoint,
		&i.CreatedAt,
	)
	return i, err
}

const insertTaskConflict = `-- name: InsertTaskConflict :one
INSERT INTO core.task_conflicts (
    task_version_id, task_id, project_id, conflicting_task_id, created_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING task_version_id, task_id, project_id, conflicting_task_id, created_at
`

type InsertTaskConflictParams struct {
	TaskVersionID     pgtype.UUID
	TaskID            pgtype.UUID
	ProjectID         pgtype.UUID
	ConflictingTaskID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertTaskConflict(ctx context.Context, arg InsertTaskConflictParams) (CoreTaskConflict, error) {
	row := q.db.QueryRow(ctx, insertTaskConflict,
		arg.TaskVersionID,
		arg.TaskID,
		arg.ProjectID,
		arg.ConflictingTaskID,
		arg.CreatedAt,
	)
	var i CoreTaskConflict
	err := row.Scan(
		&i.TaskVersionID,
		&i.TaskID,
		&i.ProjectID,
		&i.ConflictingTaskID,
		&i.CreatedAt,
	)
	return i, err
}

const insertTaskDependency = `-- name: InsertTaskDependency :one
INSERT INTO core.task_dependencies (
    task_version_id, task_id, project_id, dependency_task_id, dependency_type, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING task_version_id, task_id, project_id, dependency_task_id, dependency_type, created_at
`

type InsertTaskDependencyParams struct {
	TaskVersionID    pgtype.UUID
	TaskID           pgtype.UUID
	ProjectID        pgtype.UUID
	DependencyTaskID pgtype.UUID
	DependencyType   string
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertTaskDependency(ctx context.Context, arg InsertTaskDependencyParams) (CoreTaskDependency, error) {
	row := q.db.QueryRow(ctx, insertTaskDependency,
		arg.TaskVersionID,
		arg.TaskID,
		arg.ProjectID,
		arg.DependencyTaskID,
		arg.DependencyType,
		arg.CreatedAt,
	)
	var i CoreTaskDependency
	err := row.Scan(
		&i.TaskVersionID,
		&i.TaskID,
		&i.ProjectID,
		&i.DependencyTaskID,
		&i.DependencyType,
		&i.CreatedAt,
	)
	return i, err
}

const insertTaskImport = `-- name: InsertTaskImport :one
INSERT INTO core.task_imports (
    id, project_id, source_artifact_id, task_id, source_name, source_sha256,
    media_type, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, project_id, source_artifact_id, task_id, source_name, source_sha256,
    media_type, status, created_at, updated_at
`

type InsertTaskImportParams struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	SourceArtifactID pgtype.UUID
	TaskID           pgtype.UUID
	SourceName       string
	SourceSha256     string
	MediaType        string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) InsertTaskImport(ctx context.Context, arg InsertTaskImportParams) (CoreTaskImport, error) {
	row := q.db.QueryRow(ctx, insertTaskImport,
		arg.ID,
		arg.ProjectID,
		arg.SourceArtifactID,
		arg.TaskID,
		arg.SourceName,
		arg.SourceSha256,
		arg.MediaType,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreTaskImport
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceArtifactID,
		&i.TaskID,
		&i.SourceName,
		&i.SourceSha256,
		&i.MediaType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTaskVersion = `-- name: InsertTaskVersion :one
INSERT INTO core.task_versions (
    id, task_id, version_number, source_artifact_id, title, goal, risk_class,
    mutation_class, network_profile, priority, read_only_investigation, scope,
    excluded_scope, verification_plan, budget, secret_requirements,
    expected_paths, operator_checkpoints, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19
)
RETURNING id, task_id, version_number, source_artifact_id, title, goal, risk_class,
    mutation_class, network_profile, priority, read_only_investigation, scope,
    excluded_scope, verification_plan, budget, secret_requirements,
    expected_paths, operator_checkpoints, created_at
`

type InsertTaskVersionParams struct {
	ID                    pgtype.UUID
	TaskID                pgtype.UUID
	VersionNumber         int32
	SourceArtifactID      pgtype.UUID
	Title                 string
	Goal                  string
	RiskClass             string
	MutationClass         string
	NetworkProfile        string
	Priority              int32
	ReadOnlyInvestigation bool
	Scope                 []byte
	ExcludedScope         []byte
	VerificationPlan      []byte
	Budget                []byte
	SecretRequirements    []byte
	ExpectedPaths         []byte
	OperatorCheckpoints   []byte
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertTaskVersion(ctx context.Context, arg InsertTaskVersionParams) (CoreTaskVersion, error) {
	row := q.db.QueryRow(ctx, insertTaskVersion,
		arg.ID,
		arg.TaskID,
		arg.VersionNumber,
		arg.SourceArtifactID,
		arg.Title,
		arg.Goal,
		arg.RiskClass,
		arg.MutationClass,
		arg.NetworkProfile,
		arg.Priority,
		arg.ReadOnlyInvestigation,
		arg.Scope,
		arg.ExcludedScope,
		arg.VerificationPlan,
		arg.Budget,
		arg.SecretRequirements,
		arg.ExpectedPaths,
		arg.OperatorCheckpoints,
		arg.CreatedAt,
	)
	var i CoreTaskVersion
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.VersionNumber,
		&i.SourceArtifactID,
		&i.Title,
		&i.Goal,
		&i.RiskClass,
		&i.MutationClass,
		&i.NetworkProfile,
		&i.Priority,
		&i.ReadOnlyInvestigation,
		&i.Scope,
		&i.ExcludedScope,
		&i.VerificationPlan,
		&i.Budget,
		&i.SecretRequirements,
		&i.ExpectedPaths,
		&i.OperatorCheckpoints,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveRuns = `-- name: ListActiveRuns :many
SELECT id, project_id, task_id, task_version_id, project_source_id, status,
    aggregate_version, admitted_task_aggregate_version, source_commit,
    source_tree, coordinator_identity, created_at, updated_at, released_at
FROM core.runs
WHERE status = 'active'
ORDER BY id
`

func (q *Queries) ListActiveRuns(ctx context.Context) ([]CoreRun, error) {
	rows, err := q.db.Query(ctx, listActiveRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoreRun
	for rows.Next() {
		var i CoreRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TaskID,
			&i.TaskVersionID,
			&i.ProjectSourceID,
			&i.Status,
			&i.AggregateVersion,
			&i.AdmittedTaskAggregateVersion,
			&i.SourceCommit,
			&i.SourceTree,
			&i.CoordinatorIdentity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReleasedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerConflicts = `-- name: ListSchedulerConflicts :many
SELECT c.task_id, c.task_version_id, c.conflicting_task_id
FROM core.task_conflicts AS c
JOIN core.tasks AS t
  ON t.id = c.task_id AND t.accepted_version_id = c.task_version_id
ORDER BY c.task_id, c.conflicting_task_id
`

type ListSchedulerConflictsRow struct {
	TaskID            pgtype.UUID
	TaskVersionID     pgtype.UUID
	ConflictingTaskID pgtype.UUID
}

func (q *Queries) ListSchedulerConflicts(ctx context.Context) ([]ListSchedulerConflictsRow, error) {
	rows, err := q.db.Query(ctx, listSchedulerConflicts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulerConflictsRow
	for rows.Next() {
		var i ListSchedulerConflictsRow
		if err := rows.Scan(&i.TaskID, &i.TaskVersionID, &i.ConflictingTaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerDependencies = `-- name: ListSchedulerDependencies :many
SELECT d.task_id, d.task_version_id, d.dependency_task_id
FROM core.task_dependencies AS d
JOIN core.tasks AS t
  ON t.id = d.task_id AND t.accepted_version_id = d.task_version_id
ORDER BY d.task_id, d.dependency_task_id
`

type ListSchedulerDependenciesRow struct {
	TaskID           pgtype.UUID
	TaskVersionID    pgtype.UUID
	DependencyTaskID pgtype.UUID
}

func (q *Queries) ListSchedulerDependencies(ctx context.Context) ([]ListSchedulerDependenciesRow, error) {
	rows, err := q.db.Query(ctx, listSchedulerDependencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulerDependenciesRow
	for rows.Next() {
		var i ListSchedulerDependenciesRow
		if err := rows.Scan(&i.TaskID, &i.TaskVersionID, &i.DependencyTaskID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerProjectSources = `-- name: ListSchedulerProjectSources :many
SELECT id, project_id, current_commit, current_tree
FROM core.project_sources
ORDER BY project_id, id
`

type ListSchedulerProjectSourcesRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	CurrentCommit string
	CurrentTree   string
}

func (q *Queries) ListSchedulerProjectSources(ctx context.Context) ([]ListSchedulerProjectSourcesRow, error) {
	rows, err := q.db.Query(ctx, listSchedulerProjectSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulerProjectSourcesRow
	for rows.Next() {
		var i ListSchedulerProjectSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CurrentCommit,
			&i.CurrentTree,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulerTasks = `-- name: ListSchedulerTasks :many
SELECT
    t.id, t.project_id, t.external_task_id, t.status, t.accepted_version_id,
    t.created_at, t.aggregate_version, p.status AS project_status,
    tv.id AS task_version_id, tv.priority AS task_priority,
    EXISTS (
        SELECT 1
        FROM core.task_acceptance_versions AS av
        JOIN core.task_acceptance_criteria AS ac
          ON ac.id = av.criterion_id AND ac.task_id = av.task_id
        WHERE av.task_id = t.id
          AND av.task_version_id = t.accepted_version_id
          AND av.verification_method = 'operator_checkpoint'
          AND ac.status = 'pending'
    ) AS awaiting_operator_checkpoint
FROM core.tasks AS t
JOIN core.projects AS p ON p.id = t.project_id
LEFT JOIN core.task_versions AS tv
  ON tv.id = t.accepted_version_id AND tv.task_id = t.id
ORDER BY t.created_at, t.id
`

type ListSchedulerTasksRow struct {
	ID                         pgtype.UUID
	ProjectID                  pgtype.UUID
	ExternalTaskID             string
	Status                     string
	AcceptedVersionID          pgtype.UUID
	CreatedAt                  pgtype.Timestamptz
	AggregateVersion           int64
	ProjectStatus              string
	TaskVersionID              pgtype.UUID
	TaskPriority               pgtype.Int4
	AwaitingOperatorCheckpoint bool
}

func (q *Queries) ListSchedulerTasks(ctx context.Context) ([]ListSchedulerTasksRow, error) {
	rows, err := q.db.Query(ctx, listSchedulerTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSchedulerTasksRow
	for rows.Next() {
		var i ListSchedulerTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ExternalTaskID,
			&i.Status,
			&i.AcceptedVersionID,
			&i.CreatedAt,
			&i.AggregateVersion,
			&i.ProjectStatus,
			&i.TaskVersionID,
			&i.TaskPriority,
			&i.AwaitingOperatorCheckpoint,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseGlobalExecutionLease = `-- name: ReleaseGlobalExecutionLease :one
UPDATE core.execution_leases
SET run_id = NULL,
    coordinator_identity = NULL,
    acquired_at = NULL,
    aggregate_version = aggregate_version + 1
WHERE lease_name = 'global-source-mutation-v1'
  AND run_id = $1
  AND coordinator_identity = $2
  AND aggregate_version = $3
RETURNING lease_name, run_id, coordinator_identity, acquired_at, aggregate_version
`

type ReleaseGlobalExecutionLeaseParams struct {
	RunID                    pgtype.UUID
	CoordinatorIdentity      pgtype.Text
	ExpectedAggregateVersion int64
}

func (q *Queries) ReleaseGlobalExecutionLease(ctx context.Context, arg ReleaseGlobalExecutionLeaseParams) (CoreExecutionLease, error) {
	row := q.db.QueryRow(ctx, releaseGlobalExecutionLease, arg.RunID, arg.CoordinatorIdentity, arg.ExpectedAggregateVersion)
	var i CoreExecutionLease
	err := row.Scan(
		&i.LeaseName,
		&i.RunID,
		&i.CoordinatorIdentity,
		&i.AcquiredAt,
		&i.AggregateVersion,
	)
	return i, err
}

const releaseRun = `-- name: ReleaseRun :one
UPDATE core.runs
SET status = 'released',
    aggregate_version = aggregate_version + 1,
    updated_at = $1,
    released_at = $1
WHERE id = $2
  AND status = 'active'
  AND aggregate_version = $3
RETURNING id, project_id, task_id, task_version_id, project_source_id, status,
    aggregate_version, admitted_task_aggregate_version, source_commit,
    source_tree, coordinator_identity, created_at, updated_at, released_at
`

type ReleaseRunParams struct {
	ReleasedAt               pgtype.Timestamptz
	RunID                    pgtype.UUID
	ExpectedAggregateVersion int64
}

func (q *Queries) ReleaseRun(ctx context.Context, arg ReleaseRunParams) (CoreRun, error) {
	row := q.db.QueryRow(ctx, releaseRun, arg.ReleasedAt, arg.RunID, arg.ExpectedAggregateVersion)
	var i CoreRun
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.TaskVersionID,
		&i.ProjectSourceID,
		&i.Status,
		&i.AggregateVersion,
		&i.AdmittedTaskAggregateVersion,
		&i.SourceCommit,
		&i.SourceTree,
		&i.CoordinatorIdentity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReleasedAt,
	)
	return i, err
}
