// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: core.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO core.events (
    id, project_id, task_id, run_id, event_type, aggregate_type, aggregate_id,
    aggregate_version, payload, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, project_id, task_id, run_id, event_type, aggregate_type, aggregate_id,
    aggregate_version, payload, created_at
`

type AppendEventParams struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	TaskID           pgtype.UUID
	RunID            pgtype.UUID
	EventType        string
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	Payload          []byte
	CreatedAt        pgtype.Timestamptz
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (CoreEvent, error) {
	row := q.db.QueryRow(ctx, appendEvent,
		arg.ID,
		arg.ProjectID,
		arg.TaskID,
		arg.RunID,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.AggregateVersion,
		arg.Payload,
		arg.CreatedAt,
	)
	var i CoreEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactBySHA256 = `-- name: GetArtifactBySHA256 :one
SELECT id, sha256, size_bytes, media_type, logical_kind, storage_path, compression, created_at
FROM core.artifacts
WHERE sha256 = $1
`

func (q *Queries) GetArtifactBySHA256(ctx context.Context, sha256 string) (CoreArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifactBySHA256, sha256)
	var i CoreArtifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.MediaType,
		&i.LogicalKind,
		&i.StoragePath,
		&i.Compression,
		&i.CreatedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, project_id, task_id, run_id, event_type, aggregate_type, aggregate_id,
    aggregate_version, payload, created_at
FROM core.events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (CoreEvent, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i CoreEvent
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.AggregateVersion,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectRegistrationByCanonicalSourcePath = `-- name: GetProjectRegistrationByCanonicalSourcePath :one
SELECT
    p.id AS project_id,
    p.name,
    p.status,
    p.created_at,
    p.updated_at,
    ps.id AS project_source_id,
    ps.canonical_source_path,
    ps.managed_repository_path,
    ps.current_commit,
    ps.current_tree,
    ps.current_branch,
    ps.default_branch,
    ps.dirty_state,
    ps.remotes
FROM core.projects AS p
JOIN core.project_sources AS ps ON ps.project_id = p.id
WHERE ps.canonical_source_path = $1
`

type GetProjectRegistrationByCanonicalSourcePathRow struct {
	ProjectID             pgtype.UUID
	Name                  string
	Status                string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	ProjectSourceID       pgtype.UUID
	CanonicalSourcePath   string
	ManagedRepositoryPath string
	CurrentCommit         string
	CurrentTree           string
	CurrentBranch         pgtype.Text
	DefaultBranch         pgtype.Text
	DirtyState            []byte
	Remotes               []byte
}

func (q *Queries) GetProjectRegistrationByCanonicalSourcePath(ctx context.Context, canonicalSourcePath string) (GetProjectRegistrationByCanonicalSourcePathRow, error) {
	row := q.db.QueryRow(ctx, getProjectRegistrationByCanonicalSourcePath, canonicalSourcePath)
	var i GetProjectRegistrationByCanonicalSourcePathRow
	err := row.Scan(
		&i.ProjectID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectSourceID,
		&i.CanonicalSourcePath,
		&i.ManagedRepositoryPath,
		&i.CurrentCommit,
		&i.CurrentTree,
		&i.CurrentBranch,
		&i.DefaultBranch,
		&i.DirtyState,
		&i.Remotes,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO core.artifacts (
    id, sha256, size_bytes, media_type, logical_kind, storage_path, compression, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, sha256, size_bytes, media_type, logical_kind, storage_path, compression, created_at
`

type InsertArtifactParams struct {
	ID          pgtype.UUID
	Sha256      string
	SizeBytes   int64
	MediaType   string
	LogicalKind string
	StoragePath string
	Compression pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (CoreArtifact, error) {
	row := q.db.QueryRow(ctx, insertArtifact,
		arg.ID,
		arg.Sha256,
		arg.SizeBytes,
		arg.MediaType,
		arg.LogicalKind,
		arg.StoragePath,
		arg.Compression,
		arg.CreatedAt,
	)
	var i CoreArtifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.MediaType,
		&i.LogicalKind,
		&i.StoragePath,
		&i.Compression,
		&i.CreatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO core.projects (
    id, name, status, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, status, created_at, updated_at
`

type InsertProjectParams struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (CoreProject, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CoreProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProjectSource = `-- name: InsertProjectSource :one
INSERT INTO core.project_sources (
    id, project_id, canonical_source_path, managed_repository_path,
    current_commit, current_tree, current_branch, default_branch,
    dirty_state, remotes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, project_id, canonical_source_path, managed_repository_path,
    current_commit, current_tree, current_branch, default_branch,
    dirty_state, remotes
`

type InsertProjectSourceParams struct {
	ID                    pgtype.UUID
	ProjectID             pgtype.UUID
	CanonicalSourcePath   string
	ManagedRepositoryPath string
	CurrentCommit         string
	CurrentTree           string
	CurrentBranch         pgtype.Text
	DefaultBranch         pgtype.Text
	DirtyState            []byte
	Remotes               []byte
}

func (q *Queries) InsertProjectSource(ctx context.Context, arg InsertProjectSourceParams) (CoreProjectSource, error) {
	row := q.db.QueryRow(ctx, insertProjectSource,
		arg.ID,
		arg.ProjectID,
		arg.CanonicalSourcePath,
		arg.ManagedRepositoryPath,
		arg.CurrentCommit,
		arg.CurrentTree,
		arg.CurrentBranch,
		arg.DefaultBranch,
		arg.DirtyState,
		arg.Remotes,
	)
	var i CoreProjectSource
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CanonicalSourcePath,
		&i.ManagedRepositoryPath,
		&i.CurrentCommit,
		&i.CurrentTree,
		&i.CurrentBranch,
		&i.DefaultBranch,
		&i.DirtyState,
		&i.Remotes,
	)
	return i, err
}
