// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreArtifact struct {
	ID          pgtype.UUID
	Sha256      string
	SizeBytes   int64
	MediaType   string
	LogicalKind string
	StoragePath string
	Compression pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type CoreArtifactProvenance struct {
	ID                   pgtype.UUID
	ArtifactID           pgtype.UUID
	ProjectID            pgtype.UUID
	TaskID               pgtype.UUID
	TaskVersionID        pgtype.UUID
	RunID                pgtype.UUID
	WorkspaceID          pgtype.UUID
	ProducerRole         string
	ProducingOperationID string
	SourceCommit         string
	SourceTree           string
	CreatedAt            pgtype.Timestamptz
}

type CoreAuditFinding struct {
	ID                   pgtype.UUID
	ProjectID            pgtype.UUID
	TaskID               pgtype.UUID
	TaskVersionID        pgtype.UUID
	RunID                pgtype.UUID
	WorkspaceID          pgtype.UUID
	IntroducedAuditRunID pgtype.UUID
	FindingKey           string
	Significance         string
	Summary              string
	RequiredCorrection   string
	SourceEvidence       []byte
	AffectedFiles        []byte
	AffectedSymbols      []byte
	CriterionImpact      []byte
	DefinitionSha256     string
	SourceCommit         string
	SourceTree           string
	CreatedAt            pgtype.Timestamptz
}

type CoreAuditFindingOccurrence struct {
	ID               pgtype.UUID
	AuditRunID       pgtype.UUID
	TaskID           pgtype.UUID
	FindingID        pgtype.UUID
	Ordinal          int32
	OccurrenceSha256 string
	CreatedAt        pgtype.Timestamptz
}

type CoreAuditRun struct {
	ID                          pgtype.UUID
	OperationID                 string
	ProjectID                   pgtype.UUID
	TaskID                      pgtype.UUID
	TaskVersionID               pgtype.UUID
	RunID                       pgtype.UUID
	WorkspaceID                 pgtype.UUID
	VerificationRunID           pgtype.UUID
	AuditKind                   string
	Disposition                 string
	Independent                 bool
	AuditorInvocationID         string
	SourceMutatingInvocationIds []byte
	DossierSchemaVersion        string
	DossierSha256               string
	Dossier                     []byte
	PromptVersion               string
	PromptSha256                string
	Prompt                      string
	ResponseSchemaVersion       string
	ResponseSchemaSha256        string
	ResponseSchema              []byte
	Model                       string
	ModelRequest                []byte
	ModelResult                 []byte
	SourceCommit                string
	SourceTree                  string
	DiffSha256                  string
	ReportArtifactID            pgtype.UUID
	ReportSha256                string
	RecordSha256                string
	StartedAt                   pgtype.Timestamptz
	CompletedAt                 pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
}

type CoreClaim struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	TaskID          pgtype.UUID
	TaskVersionID   pgtype.UUID
	RunID           pgtype.UUID
	CriterionID     pgtype.UUID
	ClaimKey        string
	Statement       string
	StatementSha256 string
	CreatedAt       pgtype.Timestamptz
}

type CoreClaimEvidence struct {
	ClaimID             pgtype.UUID
	ProjectID           pgtype.UUID
	TaskID              pgtype.UUID
	TaskVersionID       pgtype.UUID
	RunID               pgtype.UUID
	Ordinal             int32
	EvidenceKind        string
	ArtifactID          pgtype.UUID
	VerificationCheckID pgtype.UUID
	EvidenceSha256      string
	CreatedAt           pgtype.Timestamptz
}

type CoreCompletion struct {
	ID                      pgtype.UUID
	OperationID             string
	ProjectID               pgtype.UUID
	TaskID                  pgtype.UUID
	TaskVersionID           pgtype.UUID
	RunID                   pgtype.UUID
	WorkspaceID             pgtype.UUID
	VerificationRunID       pgtype.UUID
	PreflightSha256         string
	EvidenceArtifactID      pgtype.UUID
	EvidenceSha256          string
	MarkdownArtifactID      pgtype.UUID
	MarkdownSha256          string
	ManifestArtifactID      pgtype.UUID
	ManifestSha256          string
	TrajectoryEnvelope      []byte
	TrajectorySha256        string
	HarnessAssetSetManifest []byte
	HarnessAssetSetSha256   string
	CompletedAt             pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
}

type CoreCompletionArtifact struct {
	CompletionID   pgtype.UUID
	Ordinal        int32
	ArtifactID     pgtype.UUID
	ArtifactSha256 string
	ArtifactRole   string
}

type CoreCompletionClaim struct {
	CompletionID  pgtype.UUID
	ProjectID     pgtype.UUID
	TaskID        pgtype.UUID
	TaskVersionID pgtype.UUID
	RunID         pgtype.UUID
	ClaimID       pgtype.UUID
}

type CoreEvent struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	TaskID           pgtype.UUID
	RunID            pgtype.UUID
	EventType        string
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	Payload          []byte
	CreatedAt        pgtype.Timestamptz
}

type CoreExecutionLease struct {
	LeaseName           string
	RunID               pgtype.UUID
	CoordinatorIdentity pgtype.Text
	AcquiredAt          pgtype.Timestamptz
	AggregateVersion    int64
}

type CoreFailureSignature struct {
	ID                  pgtype.UUID
	OperationID         string
	ProjectID           pgtype.UUID
	TaskID              pgtype.UUID
	TaskVersionID       pgtype.UUID
	RunID               pgtype.UUID
	WorkspaceID         pgtype.UUID
	AuthorityKind       string
	VerificationRunID   pgtype.UUID
	VerificationCheckID pgtype.UUID
	AuditRunID          pgtype.UUID
	FindingKeys         []byte
	SourceCommit        string
	SourceTree          string
	NormalizedMaterial  []byte
	SignatureSha256     string
	CreatedAt           pgtype.Timestamptz
}

type CoreFindingDisposition struct {
	ID                          pgtype.UUID
	OperationID                 string
	FindingID                   pgtype.UUID
	TaskID                      pgtype.UUID
	Status                      string
	AuthorityRole               string
	AuthorityID                 string
	ResolutionVerificationRunID pgtype.UUID
	ResolutionAuditRunID        pgtype.UUID
	SupersedingFindingID        pgtype.UUID
	SourceCommit                string
	SourceTree                  string
	Evidence                    []byte
	Rationale                   string
	RecordSha256                string
	CreatedAt                   pgtype.Timestamptz
}

type CorePlan struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	TaskID              pgtype.UUID
	TaskVersionID       pgtype.UUID
	RunID               pgtype.UUID
	ProjectSourceID     pgtype.UUID
	SourceRevision      string
	SourceCommit        string
	SourceTree          string
	AcceptedVersionID   pgtype.UUID
	AcceptedOperationID pgtype.Text
	AcceptedBy          pgtype.Text
	AcceptedAt          pgtype.Timestamptz
	AggregateVersion    int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type CorePlanStep struct {
	PlanVersionID    pgtype.UUID
	PlanID           pgtype.UUID
	StepID           string
	Ordinal          int32
	Status           string
	Description      string
	CriterionIds     []byte
	DependsOnStepIds []byte
	ExpectedPaths    []byte
	Components       []byte
	TestStrategy     []byte
	Risks            []byte
	Assumptions      []byte
	EvidenceRefs     []byte
	Lineage          []byte
}

type CorePlanVersion struct {
	ID                       pgtype.UUID
	PlanID                   pgtype.UUID
	TaskID                   pgtype.UUID
	TaskVersionID            pgtype.UUID
	RunID                    pgtype.UUID
	ProjectSourceID          pgtype.UUID
	RevisionNumber           int32
	SupersedesVersionID      pgtype.UUID
	CandidateSha256          string
	ContentSha256            string
	ChangeExplanation        string
	SourceRevision           string
	SupervisorDecisionID     string
	SupervisorDecisionSha256 string
	DossierVersion           string
	DossierSha256            string
	DossierContent           []byte
	PromptVersion            string
	PromptSha256             string
	PromptContent            []byte
	ResponseSchemaVersion    string
	ResponseSchemaSha256     string
	ResponseSchema           []byte
	ModelPolicyVersion       string
	ModelPolicySha256        string
	ModelPolicy              []byte
	HostPolicyVersion        string
	HostPolicySha256         string
	HostPolicy               []byte
	ExpectedRequest          []byte
	ModelResult              []byte
	RawOutput                []byte
	CanonicalOutput          []byte
	CreatedAt                pgtype.Timestamptz
}

type CoreProject struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CoreProjectSource struct {
	ID                    pgtype.UUID
	ProjectID             pgtype.UUID
	CanonicalSourcePath   string
	ManagedRepositoryPath string
	CurrentCommit         string
	CurrentTree           string
	CurrentBranch         pgtype.Text
	DefaultBranch         pgtype.Text
	DirtyState            []byte
	Remotes               []byte
}

type CoreQueueOperation struct {
	ID                        pgtype.UUID
	SchemaVersion             string
	Status                    string
	WorkerMode                string
	MaximumWorkers            int16
	QualityGateStatus         string
	ConfigSchema              string
	ConfigSha256              string
	Configuration             []byte
	MaxTasks                  int64
	MaxCyclesPerTask          int64
	MaxTotalCycles            int64
	MaxRemoteTokens           int64
	MaxCostMicrousd           int64
	MaxDurationMilliseconds   int64
	TasksStarted              int64
	CyclesConsumed            int64
	RemoteTokensConsumed      int64
	CostMicrousdConsumed      int64
	PeakSourceMutatingWorkers int16
	NextOccurrenceSequence    int64
	SelectionIntentID         pgtype.UUID
	SelectionSchedulerRunID   pgtype.UUID
	SelectionIntentSequence   pgtype.Int8
	ActiveOccurrenceID        pgtype.UUID
	CancelRequestedAt         pgtype.Timestamptz
	StartedAt                 pgtype.Timestamptz
	DeadlineAt                pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
	TerminalAt                pgtype.Timestamptz
	StopReason                pgtype.Text
	StopDetail                pgtype.Text
	TerminalMarkerSha256      pgtype.Text
	AggregateVersion          int64
}

type CoreQueueTaskEffect struct {
	ID               pgtype.UUID
	QueueOperationID pgtype.UUID
	TaskOccurrenceID pgtype.UUID
	EffectSequence   int64
	EffectKind       string
	EffectIdentity   string
	MaterialSha256   string
	Status           string
	EvidenceSha256   pgtype.Text
	IntendedAt       pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

type CoreQueueTaskOccurrence struct {
	ID                           pgtype.UUID
	QueueOperationID             pgtype.UUID
	OccurrenceSequence           int64
	State                        string
	SchedulerRunID               pgtype.UUID
	CoordinatorIdentity          string
	ProjectID                    pgtype.UUID
	ProjectSourceID              pgtype.UUID
	TaskID                       pgtype.UUID
	TaskVersionID                pgtype.UUID
	ExternalTaskID               pgtype.Text
	ExpectedTaskAggregateVersion pgtype.Int8
	TaskPriority                 pgtype.Int4
	TaskCreatedAt                pgtype.Timestamptz
	SourceCommit                 pgtype.Text
	SourceTree                   pgtype.Text
	Selection                    []byte
	SelectionSha256              pgtype.Text
	Outcome                      pgtype.Text
	OutcomeDetail                pgtype.Text
	Result                       []byte
	ResultSha256                 pgtype.Text
	EffectChainSha256            pgtype.Text
	CyclesConsumed               pgtype.Int8
	RemoteTokensConsumed         pgtype.Int8
	CostMicrousdConsumed         pgtype.Int8
	WorkspaceReconciled          pgtype.Bool
	EvidenceReconciled           pgtype.Bool
	LeaseReconciled              bool
	SelectedAt                   pgtype.Timestamptz
	AdmittedAt                   pgtype.Timestamptz
	RunnerTerminalAt             pgtype.Timestamptz
	CheckpointedAt               pgtype.Timestamptz
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
}

type CoreRun struct {
	ID                           pgtype.UUID
	ProjectID                    pgtype.UUID
	TaskID                       pgtype.UUID
	TaskVersionID                pgtype.UUID
	ProjectSourceID              pgtype.UUID
	Status                       string
	AggregateVersion             int64
	AdmittedTaskAggregateVersion int64
	SourceCommit                 string
	SourceTree                   string
	CoordinatorIdentity          string
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	ReleasedAt                   pgtype.Timestamptz
}

type CoreStrategy struct {
	ID                         pgtype.UUID
	OperationID                string
	ProjectID                  pgtype.UUID
	TaskID                     pgtype.UUID
	TaskVersionID              pgtype.UUID
	RunID                      pgtype.UUID
	WorkspaceID                pgtype.UUID
	FailureSignatureID         pgtype.UUID
	SourceCommit               string
	SourceTree                 string
	DossierSha256              string
	StrategyFingerprint        string
	NormalizedStrategy         []byte
	CorrectorInvocationID      string
	SandboxSpecificationSha256 string
	CreatedAt                  pgtype.Timestamptz
}

type CoreStrategyOutcome struct {
	ID                    pgtype.UUID
	StrategyID            pgtype.UUID
	TaskID                pgtype.UUID
	Outcome               string
	ResultingSourceCommit pgtype.Text
	ResultingSourceTree   pgtype.Text
	DiffSha256            pgtype.Text
	VerificationRunID     pgtype.UUID
	AuditRunID            pgtype.UUID
	Evidence              []byte
	RecordSha256          string
	CompletedAt           pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
}

type CoreTask struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	ExternalTaskID    string
	Status            string
	AcceptedVersionID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	AggregateVersion  int64
}

type CoreTaskAcceptanceCriterium struct {
	ID                  pgtype.UUID
	TaskID              pgtype.UUID
	ExternalCriterionID string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type CoreTaskAcceptanceVersion struct {
	ID                    pgtype.UUID
	CriterionID           pgtype.UUID
	TaskID                pgtype.UUID
	TaskVersionID         pgtype.UUID
	VersionNumber         int32
	Requirement           string
	VerificationMethod    string
	VerificationReference pgtype.Text
	OperatorCheckpoint    []byte
	CreatedAt             pgtype.Timestamptz
}

type CoreTaskConflict struct {
	TaskVersionID     pgtype.UUID
	TaskID            pgtype.UUID
	ProjectID         pgtype.UUID
	ConflictingTaskID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

type CoreTaskDependency struct {
	TaskVersionID    pgtype.UUID
	TaskID           pgtype.UUID
	ProjectID        pgtype.UUID
	DependencyTaskID pgtype.UUID
	DependencyType   string
	CreatedAt        pgtype.Timestamptz
}

type CoreTaskImport struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	SourceArtifactID pgtype.UUID
	TaskID           pgtype.UUID
	SourceName       string
	SourceSha256     string
	MediaType        string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type CoreTaskVersion struct {
	ID                    pgtype.UUID
	TaskID                pgtype.UUID
	VersionNumber         int32
	SourceArtifactID      pgtype.UUID
	Title                 string
	Goal                  string
	RiskClass             string
	MutationClass         string
	NetworkProfile        string
	Priority              int32
	ReadOnlyInvestigation bool
	Scope                 []byte
	ExcludedScope         []byte
	VerificationPlan      []byte
	Budget                []byte
	SecretRequirements    []byte
	ExpectedPaths         []byte
	OperatorCheckpoints   []byte
	CreatedAt             pgtype.Timestamptz
}

type CoreVerificationCheck struct {
	ID                            pgtype.UUID
	VerificationRunID             pgtype.UUID
	RunID                         pgtype.UUID
	Ordinal                       int32
	GateID                        string
	Tier                          int16
	Outcome                       string
	ExecutionFingerprint          string
	VerifierProtocolVersion       string
	VerifierImplementationVersion string
	ParserKind                    string
	ParserVersion                 string
	SourceCommit                  string
	SourceTree                    string
	CommandArgv                   []byte
	WorkingDirectory              string
	Environment                   []byte
	ImageReference                string
	ImageDigest                   string
	SandboxProfile                string
	SandboxProfileSha256          string
	SandboxSpecificationSha256    string
	AuthorityInputs               []byte
	OutputPolicy                  []byte
	ExitCode                      pgtype.Int4
	TimedOut                      bool
	Cancelled                     bool
	StdoutArtifactID              pgtype.UUID
	StderrArtifactID              pgtype.UUID
	ParsedResult                  []byte
	SandboxEvidence               []byte
	FailureSignatures             []byte
	ReusedFromCheckID             pgtype.UUID
	OriginalExecutedAt            pgtype.Timestamptz
	OccurredAt                    pgtype.Timestamptz
	StartedAt                     pgtype.Timestamptz
	CompletedAt                   pgtype.Timestamptz
	CreatedAt                     pgtype.Timestamptz
}

type CoreVerificationRun struct {
	ID                       pgtype.UUID
	ProjectID                pgtype.UUID
	TaskID                   pgtype.UUID
	TaskVersionID            pgtype.UUID
	RunID                    pgtype.UUID
	WorkspaceID              pgtype.UUID
	Purpose                  string
	Status                   string
	PlanSchemaVersion        string
	PlanVersion              string
	PlanSha256               string
	PinnedPlan               []byte
	CandidateCommit          string
	CandidateTree            string
	ProjectEnvironmentSha256 string
	ProjectEnvironment       []byte
	Differential             []byte
	StartedAt                pgtype.Timestamptz
	CompletedAt              pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
}

type CoreWorkspace struct {
	ID                     pgtype.UUID
	RunID                  pgtype.UUID
	ProjectID              pgtype.UUID
	ProjectSourceID        pgtype.UUID
	TaskID                 pgtype.UUID
	CreationOperationID    string
	SymbolicSourceID       string
	Status                 string
	TerminalStatus         pgtype.Text
	AggregateVersion       int64
	OriginalCheckoutPath   string
	ManagedRepositoryPath  string
	WorkspaceRoot          string
	WorkspacePath          string
	BranchRef              string
	SourceCommit           string
	SourceTree             string
	WorkspaceDevice        pgtype.Int8
	WorkspaceInode         pgtype.Int8
	OriginalIdentityBefore []byte
	OriginalIdentityAfter  []byte
	GitStatus              []byte
	ChangedManifest        []byte
	DiffArtifactID         pgtype.UUID
	DiffSha256             pgtype.Text
	CandidateCommit        pgtype.Text
	CandidateTree          pgtype.Text
	TerminalReason         pgtype.Text
	CleanupCompletedAt     pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type CoreWorkspaceOperation struct {
	OperationID    string
	WorkspaceID    pgtype.UUID
	OperationKind  string
	MaterialSha256 string
	Status         string
	Effect         []byte
	CreatedAt      pgtype.Timestamptz
	AppliedAt      pgtype.Timestamptz
}

type RetrievalChunk struct {
	ID                   pgtype.UUID
	DocumentVersionID    pgtype.UUID
	ChunkOrdinal         int32
	ChunkKind            string
	Language             string
	SymbolName           pgtype.Text
	Signature            string
	StartLine            int32
	EndLine              int32
	Body                 string
	BodySha256           string
	StructuralProvenance []byte
	SearchVector         interface{}
	CreatedAt            pgtype.Timestamptz
}

type RetrievalChunkEmbedding struct {
	ChunkID              pgtype.UUID
	EmbeddingSpaceID     pgtype.UUID
	Dimensions           int32
	Embedding            string
	EmbeddingInputSha256 string
	CreatedAt            pgtype.Timestamptz
}

type RetrievalDocument struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	FilePath  string
	Language  string
	CreatedAt pgtype.Timestamptz
}

type RetrievalDocumentVersion struct {
	ID                   pgtype.UUID
	DocumentID           pgtype.UUID
	ContentSha256        string
	SizeBytes            int64
	StructuralProvenance []byte
	CreatedAt            pgtype.Timestamptz
}

type RetrievalEmbeddingSpace struct {
	ID                 pgtype.UUID
	SpaceSha256        string
	SchemaVersion      string
	ModelName          string
	ModelRevision      string
	Dimensions         int32
	Pooling            string
	Normalization      string
	Quantization       string
	ArtifactSha256     string
	License            string
	SourceUri          string
	ServingImageDigest string
	CreatedAt          pgtype.Timestamptz
}

type RetrievalIndexBuild struct {
	ID                    pgtype.UUID
	OperationID           string
	ProjectID             pgtype.UUID
	SourceRevision        string
	SourceTree            string
	EmbeddingSpaceID      pgtype.UUID
	PreviousActiveBuildID pgtype.UUID
	BuildKind             string
	Status                string
	ManifestSha256        string
	FileCount             int32
	ChunkCount            int32
	SymbolCount           int32
	VectorCount           int32
	ErrorCode             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	CompletedAt           pgtype.Timestamptz
}

type RetrievalIndexBuildChunk struct {
	BuildID pgtype.UUID
	ChunkID pgtype.UUID
}

type RetrievalIndexBuildDocument struct {
	BuildID           pgtype.UUID
	DocumentVersionID pgtype.UUID
	FilePath          string
	ContentSha256     string
	Reused            bool
}

type RetrievalIndexBuildSymbol struct {
	BuildID  pgtype.UUID
	SymbolID pgtype.UUID
}

type RetrievalIndexState struct {
	ProjectID              pgtype.UUID
	Status                 string
	ActiveBuildID          pgtype.UUID
	ActiveSourceRevision   pgtype.Text
	ActiveEmbeddingSpaceID pgtype.UUID
	LastBuildID            pgtype.UUID
	Detail                 string
	UpdatedAt              pgtype.Timestamptz
}

type RetrievalRelation struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	BuildID         pgtype.UUID
	SubjectKind     string
	SubjectIdentity string
	Predicate       string
	ObjectKind      string
	ObjectIdentity  string
	AuthorityClass  string
	CreatedAt       pgtype.Timestamptz
}

type RetrievalRelationSource struct {
	RelationID     pgtype.UUID
	SourceKind     string
	SourceIdentity string
	SourceSha256   string
	ArtifactID     pgtype.UUID
	Provenance     []byte
}

type RetrievalSymbol struct {
	ID                pgtype.UUID
	DocumentVersionID pgtype.UUID
	ChunkID           pgtype.UUID
	SymbolName        string
	SymbolKind        string
	Signature         string
	StartLine         int32
	EndLine           int32
	CreatedAt         pgtype.Timestamptz
}

type RetrievalSymbolEdge struct {
	ID                pgtype.UUID
	DocumentVersionID pgtype.UUID
	FromSymbolID      pgtype.UUID
	EdgeKind          string
	TargetSymbol      string
	TargetPath        pgtype.Text
	SourceLine        int32
	Provenance        []byte
	CreatedAt         pgtype.Timestamptz
}

type TelemetryContextItem struct {
	ContextPackageID      pgtype.UUID
	Ordinal               int32
	CandidateIdentity     string
	AuthorityClass        string
	SourceKind            string
	SourceIdentity        string
	SourceSha256          string
	SourcePath            pgtype.Text
	SymbolName            pgtype.Text
	StartLine             pgtype.Int4
	EndLine               pgtype.Int4
	RankingSignals        []byte
	Included              bool
	StorageForm           string
	InlineContent         pgtype.Text
	ArtifactID            pgtype.UUID
	ArtifactSha256        pgtype.Text
	RangeStart            pgtype.Int8
	RangeEnd              pgtype.Int8
	TrajectoryID          pgtype.Text
	TrajectoryStart       pgtype.Int8
	TrajectoryEnd         pgtype.Int8
	MediaType             pgtype.Text
	RetrievalInstructions []byte
	OmissionReason        pgtype.Text
}

type TelemetryContextPackage struct {
	ID                     pgtype.UUID
	ProjectID              pgtype.UUID
	TaskID                 pgtype.UUID
	RunID                  pgtype.UUID
	SchemaVersion          string
	Role                   string
	SourceRevision         string
	EmbeddingSpaceID       pgtype.UUID
	ByteBudget             int32
	TokenBudget            int32
	FinalBytes             int32
	FinalTokens            int32
	TokenEstimator         string
	RetrievalConfiguration []byte
	Manifest               []byte
	Dossier                []byte
	DossierSha256          string
	CreatedAt              pgtype.Timestamptz
}
