// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreArtifact struct {
	ID          pgtype.UUID
	Sha256      string
	SizeBytes   int64
	MediaType   string
	LogicalKind string
	StoragePath string
	Compression pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type CoreEvent struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	TaskID           pgtype.UUID
	RunID            pgtype.UUID
	EventType        string
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	Payload          []byte
	CreatedAt        pgtype.Timestamptz
}

type CoreProject struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CoreProjectSource struct {
	ID                    pgtype.UUID
	ProjectID             pgtype.UUID
	CanonicalSourcePath   string
	ManagedRepositoryPath string
	CurrentCommit         string
	CurrentTree           string
	CurrentBranch         pgtype.Text
	DefaultBranch         pgtype.Text
	DirtyState            []byte
	Remotes               []byte
}
