// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoreArtifact struct {
	ID          pgtype.UUID
	Sha256      string
	SizeBytes   int64
	MediaType   string
	LogicalKind string
	StoragePath string
	Compression pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type CoreEvent struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	TaskID           pgtype.UUID
	RunID            pgtype.UUID
	EventType        string
	AggregateType    string
	AggregateID      pgtype.UUID
	AggregateVersion int64
	Payload          []byte
	CreatedAt        pgtype.Timestamptz
}

type CoreExecutionLease struct {
	LeaseName           string
	RunID               pgtype.UUID
	CoordinatorIdentity pgtype.Text
	AcquiredAt          pgtype.Timestamptz
	AggregateVersion    int64
}

type CoreProject struct {
	ID        pgtype.UUID
	Name      string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type CoreProjectSource struct {
	ID                    pgtype.UUID
	ProjectID             pgtype.UUID
	CanonicalSourcePath   string
	ManagedRepositoryPath string
	CurrentCommit         string
	CurrentTree           string
	CurrentBranch         pgtype.Text
	DefaultBranch         pgtype.Text
	DirtyState            []byte
	Remotes               []byte
}

type CoreRun struct {
	ID                           pgtype.UUID
	ProjectID                    pgtype.UUID
	TaskID                       pgtype.UUID
	TaskVersionID                pgtype.UUID
	ProjectSourceID              pgtype.UUID
	Status                       string
	AggregateVersion             int64
	AdmittedTaskAggregateVersion int64
	SourceCommit                 string
	SourceTree                   string
	CoordinatorIdentity          string
	CreatedAt                    pgtype.Timestamptz
	UpdatedAt                    pgtype.Timestamptz
	ReleasedAt                   pgtype.Timestamptz
}

type CoreTask struct {
	ID                pgtype.UUID
	ProjectID         pgtype.UUID
	ExternalTaskID    string
	Status            string
	AcceptedVersionID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	AggregateVersion  int64
}

type CoreTaskAcceptanceCriterium struct {
	ID                  pgtype.UUID
	TaskID              pgtype.UUID
	ExternalCriterionID string
	Status              string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type CoreTaskAcceptanceVersion struct {
	ID                    pgtype.UUID
	CriterionID           pgtype.UUID
	TaskID                pgtype.UUID
	TaskVersionID         pgtype.UUID
	VersionNumber         int32
	Requirement           string
	VerificationMethod    string
	VerificationReference pgtype.Text
	OperatorCheckpoint    []byte
	CreatedAt             pgtype.Timestamptz
}

type CoreTaskConflict struct {
	TaskVersionID     pgtype.UUID
	TaskID            pgtype.UUID
	ProjectID         pgtype.UUID
	ConflictingTaskID pgtype.UUID
	CreatedAt         pgtype.Timestamptz
}

type CoreTaskDependency struct {
	TaskVersionID    pgtype.UUID
	TaskID           pgtype.UUID
	ProjectID        pgtype.UUID
	DependencyTaskID pgtype.UUID
	DependencyType   string
	CreatedAt        pgtype.Timestamptz
}

type CoreTaskImport struct {
	ID               pgtype.UUID
	ProjectID        pgtype.UUID
	SourceArtifactID pgtype.UUID
	TaskID           pgtype.UUID
	SourceName       string
	SourceSha256     string
	MediaType        string
	Status           string
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type CoreTaskVersion struct {
	ID                    pgtype.UUID
	TaskID                pgtype.UUID
	VersionNumber         int32
	SourceArtifactID      pgtype.UUID
	Title                 string
	Goal                  string
	RiskClass             string
	MutationClass         string
	NetworkProfile        string
	Priority              int32
	ReadOnlyInvestigation bool
	Scope                 []byte
	ExcludedScope         []byte
	VerificationPlan      []byte
	Budget                []byte
	SecretRequirements    []byte
	ExpectedPaths         []byte
	OperatorCheckpoints   []byte
	CreatedAt             pgtype.Timestamptz
}
