// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: retrieval.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateIndexBuild = `-- name: ActivateIndexBuild :exec
UPDATE retrieval.index_states AS ist
SET status = 'clean', active_build_id = ib.id,
    active_source_revision = ib.source_revision,
    active_embedding_space_id = ib.embedding_space_id,
    last_build_id = ib.id, detail = '', updated_at = $2
FROM retrieval.index_builds AS ib
WHERE ist.project_id = $1 AND ib.id = $3 AND ib.project_id = ist.project_id
  AND ib.status = 'clean'
`

type ActivateIndexBuildParams struct {
	ProjectID pgtype.UUID
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) ActivateIndexBuild(ctx context.Context, arg ActivateIndexBuildParams) error {
	_, err := q.db.Exec(ctx, activateIndexBuild, arg.ProjectID, arg.UpdatedAt, arg.ID)
	return err
}

const completeIndexBuild = `-- name: CompleteIndexBuild :exec
UPDATE retrieval.index_builds
SET status = 'clean', completed_at = $2
WHERE id = $1 AND status = 'building'
`

type CompleteIndexBuildParams struct {
	ID          pgtype.UUID
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) CompleteIndexBuild(ctx context.Context, arg CompleteIndexBuildParams) error {
	_, err := q.db.Exec(ctx, completeIndexBuild, arg.ID, arg.CompletedAt)
	return err
}

const countIndexBuildRows = `-- name: CountIndexBuildRows :one
SELECT
    (SELECT count(*) FROM retrieval.index_build_documents AS ibd WHERE ibd.build_id = $1) AS file_count,
    (SELECT count(*) FROM retrieval.index_build_chunks AS ibc_count WHERE ibc_count.build_id = $1) AS chunk_count,
    (SELECT count(*) FROM retrieval.index_build_symbols AS ibs WHERE ibs.build_id = $1) AS symbol_count,
    (SELECT count(*) FROM retrieval.index_build_chunks AS ibc
        JOIN retrieval.chunk_embeddings AS ce ON ce.chunk_id = ibc.chunk_id
        JOIN retrieval.index_builds AS ib ON ib.id = ibc.build_id
        WHERE ibc.build_id = $1
          AND ce.embedding_space_id = ib.embedding_space_id) AS vector_count
`

type CountIndexBuildRowsRow struct {
	FileCount   int64
	ChunkCount  int64
	SymbolCount int64
	VectorCount int64
}

func (q *Queries) CountIndexBuildRows(ctx context.Context, targetBuildID pgtype.UUID) (CountIndexBuildRowsRow, error) {
	row := q.db.QueryRow(ctx, countIndexBuildRows, targetBuildID)
	var i CountIndexBuildRowsRow
	err := row.Scan(
		&i.FileCount,
		&i.ChunkCount,
		&i.SymbolCount,
		&i.VectorCount,
	)
	return i, err
}

const exactFileChunks = `-- name: ExactFileChunks :many
SELECT c.id AS chunk_id, d.file_path, c.language, c.symbol_name, c.signature,
    c.chunk_kind, c.start_line, c.end_line, c.body, c.body_sha256,
    ib.source_revision
FROM retrieval.index_states AS ist
JOIN retrieval.index_builds AS ib ON ib.id = ist.active_build_id
JOIN retrieval.index_build_chunks AS ibc ON ibc.build_id = ib.id
JOIN retrieval.chunks AS c ON c.id = ibc.chunk_id
JOIN retrieval.document_versions AS dv ON dv.id = c.document_version_id
JOIN retrieval.documents AS d ON d.id = dv.document_id
WHERE ist.project_id = $1
  AND d.file_path = ANY($2::text[])
ORDER BY array_position($2::text[], d.file_path), c.start_line, c.id
LIMIT $3
`

type ExactFileChunksParams struct {
	ProjectID   pgtype.UUID
	FilePaths   []string
	ResultLimit int32
}

type ExactFileChunksRow struct {
	ChunkID        pgtype.UUID
	FilePath       string
	Language       string
	SymbolName     pgtype.Text
	Signature      string
	ChunkKind      string
	StartLine      int32
	EndLine        int32
	Body           string
	BodySha256     string
	SourceRevision string
}

func (q *Queries) ExactFileChunks(ctx context.Context, arg ExactFileChunksParams) ([]ExactFileChunksRow, error) {
	rows, err := q.db.Query(ctx, exactFileChunks, arg.ProjectID, arg.FilePaths, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExactFileChunksRow
	for rows.Next() {
		var i ExactFileChunksRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.FilePath,
			&i.Language,
			&i.SymbolName,
			&i.Signature,
			&i.ChunkKind,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.BodySha256,
			&i.SourceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exactSymbolChunks = `-- name: ExactSymbolChunks :many
SELECT c.id AS chunk_id, d.file_path, c.language, c.symbol_name, c.signature,
    c.chunk_kind, c.start_line, c.end_line, c.body, c.body_sha256,
    ib.source_revision
FROM retrieval.index_states AS ist
JOIN retrieval.index_builds AS ib ON ib.id = ist.active_build_id
JOIN retrieval.index_build_symbols AS ibs ON ibs.build_id = ib.id
JOIN retrieval.symbols AS s ON s.id = ibs.symbol_id
JOIN retrieval.chunks AS c ON c.id = s.chunk_id
JOIN retrieval.document_versions AS dv ON dv.id = c.document_version_id
JOIN retrieval.documents AS d ON d.id = dv.document_id
WHERE ist.project_id = $1
  AND lower(s.symbol_name) = ANY($2::text[])
ORDER BY array_position($2::text[], lower(s.symbol_name)), d.file_path, c.start_line, c.id
LIMIT $3
`

type ExactSymbolChunksParams struct {
	ProjectID   pgtype.UUID
	SymbolNames []string
	ResultLimit int32
}

type ExactSymbolChunksRow struct {
	ChunkID        pgtype.UUID
	FilePath       string
	Language       string
	SymbolName     pgtype.Text
	Signature      string
	ChunkKind      string
	StartLine      int32
	EndLine        int32
	Body           string
	BodySha256     string
	SourceRevision string
}

func (q *Queries) ExactSymbolChunks(ctx context.Context, arg ExactSymbolChunksParams) ([]ExactSymbolChunksRow, error) {
	rows, err := q.db.Query(ctx, exactSymbolChunks, arg.ProjectID, arg.SymbolNames, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExactSymbolChunksRow
	for rows.Next() {
		var i ExactSymbolChunksRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.FilePath,
			&i.Language,
			&i.SymbolName,
			&i.Signature,
			&i.ChunkKind,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.BodySha256,
			&i.SourceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exactTextChunks = `-- name: ExactTextChunks :many
SELECT c.id AS chunk_id, d.file_path, c.language, c.symbol_name, c.signature,
    c.chunk_kind, c.start_line, c.end_line, c.body, c.body_sha256,
    ib.source_revision
FROM retrieval.index_states AS ist
JOIN retrieval.index_builds AS ib ON ib.id = ist.active_build_id
JOIN retrieval.index_build_chunks AS ibc ON ibc.build_id = ib.id
JOIN retrieval.chunks AS c ON c.id = ibc.chunk_id
JOIN retrieval.document_versions AS dv ON dv.id = c.document_version_id
JOIN retrieval.documents AS d ON d.id = dv.document_id
WHERE ist.project_id = $1
  AND position(lower($2) in lower(c.body)) > 0
ORDER BY d.file_path, c.start_line, c.id
LIMIT $3
`

type ExactTextChunksParams struct {
	ProjectID   pgtype.UUID
	Query       string
	ResultLimit int32
}

type ExactTextChunksRow struct {
	ChunkID        pgtype.UUID
	FilePath       string
	Language       string
	SymbolName     pgtype.Text
	Signature      string
	ChunkKind      string
	StartLine      int32
	EndLine        int32
	Body           string
	BodySha256     string
	SourceRevision string
}

func (q *Queries) ExactTextChunks(ctx context.Context, arg ExactTextChunksParams) ([]ExactTextChunksRow, error) {
	rows, err := q.db.Query(ctx, exactTextChunks, arg.ProjectID, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExactTextChunksRow
	for rows.Next() {
		var i ExactTextChunksRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.FilePath,
			&i.Language,
			&i.SymbolName,
			&i.Signature,
			&i.ChunkKind,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.BodySha256,
			&i.SourceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fTSChunks = `-- name: FTSChunks :many
SELECT c.id AS chunk_id, d.file_path, c.language, c.symbol_name, c.signature,
    c.chunk_kind, c.start_line, c.end_line, c.body, c.body_sha256,
    ib.source_revision,
    ts_rank_cd(c.search_vector, to_tsquery('simple', $1), 32)::double precision AS lexical_score
FROM retrieval.index_states AS ist
JOIN retrieval.index_builds AS ib ON ib.id = ist.active_build_id
JOIN retrieval.index_build_chunks AS ibc ON ibc.build_id = ib.id
JOIN retrieval.chunks AS c ON c.id = ibc.chunk_id
JOIN retrieval.document_versions AS dv ON dv.id = c.document_version_id
JOIN retrieval.documents AS d ON d.id = dv.document_id
WHERE ist.project_id = $2
  AND c.search_vector @@ to_tsquery('simple', $1)
ORDER BY lexical_score DESC, d.file_path, c.start_line, c.id
LIMIT $3
`

type FTSChunksParams struct {
	Query       string
	ProjectID   pgtype.UUID
	ResultLimit int32
}

type FTSChunksRow struct {
	ChunkID        pgtype.UUID
	FilePath       string
	Language       string
	SymbolName     pgtype.Text
	Signature      string
	ChunkKind      string
	StartLine      int32
	EndLine        int32
	Body           string
	BodySha256     string
	SourceRevision string
	LexicalScore   float64
}

func (q *Queries) FTSChunks(ctx context.Context, arg FTSChunksParams) ([]FTSChunksRow, error) {
	rows, err := q.db.Query(ctx, fTSChunks, arg.Query, arg.ProjectID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FTSChunksRow
	for rows.Next() {
		var i FTSChunksRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.FilePath,
			&i.Language,
			&i.SymbolName,
			&i.Signature,
			&i.ChunkKind,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.BodySha256,
			&i.SourceRevision,
			&i.LexicalScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failIndexBuild = `-- name: FailIndexBuild :exec
UPDATE retrieval.index_builds
SET status = 'failed', error_code = $2, completed_at = $3
WHERE id = $1 AND status = 'building'
`

type FailIndexBuildParams struct {
	ID          pgtype.UUID
	ErrorCode   pgtype.Text
	CompletedAt pgtype.Timestamptz
}

func (q *Queries) FailIndexBuild(ctx context.Context, arg FailIndexBuildParams) error {
	_, err := q.db.Exec(ctx, failIndexBuild, arg.ID, arg.ErrorCode, arg.CompletedAt)
	return err
}

const getChunkEmbeddingIdentity = `-- name: GetChunkEmbeddingIdentity :one
SELECT chunk_id, embedding_space_id, dimensions, embedding_input_sha256,
    embedding::text AS embedding_text, created_at
FROM retrieval.chunk_embeddings
WHERE chunk_id = $1 AND embedding_space_id = $2
`

type GetChunkEmbeddingIdentityParams struct {
	ChunkID          pgtype.UUID
	EmbeddingSpaceID pgtype.UUID
}

type GetChunkEmbeddingIdentityRow struct {
	ChunkID              pgtype.UUID
	EmbeddingSpaceID     pgtype.UUID
	Dimensions           int32
	EmbeddingInputSha256 string
	EmbeddingText        string
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) GetChunkEmbeddingIdentity(ctx context.Context, arg GetChunkEmbeddingIdentityParams) (GetChunkEmbeddingIdentityRow, error) {
	row := q.db.QueryRow(ctx, getChunkEmbeddingIdentity, arg.ChunkID, arg.EmbeddingSpaceID)
	var i GetChunkEmbeddingIdentityRow
	err := row.Scan(
		&i.ChunkID,
		&i.EmbeddingSpaceID,
		&i.Dimensions,
		&i.EmbeddingInputSha256,
		&i.EmbeddingText,
		&i.CreatedAt,
	)
	return i, err
}

const getContextItemByCandidate = `-- name: GetContextItemByCandidate :one
SELECT context_package_id, ordinal, candidate_identity, authority_class,
    source_kind, source_identity, source_sha256, source_path, symbol_name,
    start_line, end_line, ranking_signals, included, storage_form,
    inline_content, artifact_id, artifact_sha256, range_start, range_end,
    trajectory_id, trajectory_start, trajectory_end, media_type,
    retrieval_instructions, omission_reason
FROM telemetry.context_items
WHERE context_package_id = $1 AND candidate_identity = $2
`

type GetContextItemByCandidateParams struct {
	ContextPackageID  pgtype.UUID
	CandidateIdentity string
}

func (q *Queries) GetContextItemByCandidate(ctx context.Context, arg GetContextItemByCandidateParams) (TelemetryContextItem, error) {
	row := q.db.QueryRow(ctx, getContextItemByCandidate, arg.ContextPackageID, arg.CandidateIdentity)
	var i TelemetryContextItem
	err := row.Scan(
		&i.ContextPackageID,
		&i.Ordinal,
		&i.CandidateIdentity,
		&i.AuthorityClass,
		&i.SourceKind,
		&i.SourceIdentity,
		&i.SourceSha256,
		&i.SourcePath,
		&i.SymbolName,
		&i.StartLine,
		&i.EndLine,
		&i.RankingSignals,
		&i.Included,
		&i.StorageForm,
		&i.InlineContent,
		&i.ArtifactID,
		&i.ArtifactSha256,
		&i.RangeStart,
		&i.RangeEnd,
		&i.TrajectoryID,
		&i.TrajectoryStart,
		&i.TrajectoryEnd,
		&i.MediaType,
		&i.RetrievalInstructions,
		&i.OmissionReason,
	)
	return i, err
}

const getContextPackage = `-- name: GetContextPackage :one
SELECT id, project_id, task_id, run_id, schema_version, role, source_revision,
    embedding_space_id, byte_budget, token_budget, final_bytes, final_tokens,
    token_estimator, retrieval_configuration, manifest, dossier, dossier_sha256, created_at
FROM telemetry.context_packages
WHERE id = $1
`

func (q *Queries) GetContextPackage(ctx context.Context, id pgtype.UUID) (TelemetryContextPackage, error) {
	row := q.db.QueryRow(ctx, getContextPackage, id)
	var i TelemetryContextPackage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TaskID,
		&i.RunID,
		&i.SchemaVersion,
		&i.Role,
		&i.SourceRevision,
		&i.EmbeddingSpaceID,
		&i.ByteBudget,
		&i.TokenBudget,
		&i.FinalBytes,
		&i.FinalTokens,
		&i.TokenEstimator,
		&i.RetrievalConfiguration,
		&i.Manifest,
		&i.Dossier,
		&i.DossierSha256,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentVersion = `-- name: GetDocumentVersion :one
SELECT id, document_id, content_sha256, size_bytes, structural_provenance, created_at
FROM retrieval.document_versions
WHERE document_id = $1 AND content_sha256 = $2
`

type GetDocumentVersionParams struct {
	DocumentID    pgtype.UUID
	ContentSha256 string
}

func (q *Queries) GetDocumentVersion(ctx context.Context, arg GetDocumentVersionParams) (RetrievalDocumentVersion, error) {
	row := q.db.QueryRow(ctx, getDocumentVersion, arg.DocumentID, arg.ContentSha256)
	var i RetrievalDocumentVersion
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ContentSha256,
		&i.SizeBytes,
		&i.StructuralProvenance,
		&i.CreatedAt,
	)
	return i, err
}

const getEmbeddingSpaceByID = `-- name: GetEmbeddingSpaceByID :one
SELECT id, space_sha256, schema_version, model_name, model_revision, dimensions,
    pooling, normalization, quantization, artifact_sha256, license, source_uri,
    serving_image_digest, created_at
FROM retrieval.embedding_spaces
WHERE id = $1
`

func (q *Queries) GetEmbeddingSpaceByID(ctx context.Context, id pgtype.UUID) (RetrievalEmbeddingSpace, error) {
	row := q.db.QueryRow(ctx, getEmbeddingSpaceByID, id)
	var i RetrievalEmbeddingSpace
	err := row.Scan(
		&i.ID,
		&i.SpaceSha256,
		&i.SchemaVersion,
		&i.ModelName,
		&i.ModelRevision,
		&i.Dimensions,
		&i.Pooling,
		&i.Normalization,
		&i.Quantization,
		&i.ArtifactSha256,
		&i.License,
		&i.SourceUri,
		&i.ServingImageDigest,
		&i.CreatedAt,
	)
	return i, err
}

const getEmbeddingSpaceBySHA256 = `-- name: GetEmbeddingSpaceBySHA256 :one
SELECT id, space_sha256, schema_version, model_name, model_revision, dimensions,
    pooling, normalization, quantization, artifact_sha256, license, source_uri,
    serving_image_digest, created_at
FROM retrieval.embedding_spaces
WHERE space_sha256 = $1
`

func (q *Queries) GetEmbeddingSpaceBySHA256(ctx context.Context, spaceSha256 string) (RetrievalEmbeddingSpace, error) {
	row := q.db.QueryRow(ctx, getEmbeddingSpaceBySHA256, spaceSha256)
	var i RetrievalEmbeddingSpace
	err := row.Scan(
		&i.ID,
		&i.SpaceSha256,
		&i.SchemaVersion,
		&i.ModelName,
		&i.ModelRevision,
		&i.Dimensions,
		&i.Pooling,
		&i.Normalization,
		&i.Quantization,
		&i.ArtifactSha256,
		&i.License,
		&i.SourceUri,
		&i.ServingImageDigest,
		&i.CreatedAt,
	)
	return i, err
}

const getIndexBuildByOperationID = `-- name: GetIndexBuildByOperationID :one
SELECT id, operation_id, project_id, source_revision, source_tree,
    embedding_space_id, previous_active_build_id, build_kind, status,
    manifest_sha256, file_count, chunk_count, symbol_count, vector_count,
    error_code, created_at, completed_at
FROM retrieval.index_builds
WHERE operation_id = $1
`

func (q *Queries) GetIndexBuildByOperationID(ctx context.Context, operationID string) (RetrievalIndexBuild, error) {
	row := q.db.QueryRow(ctx, getIndexBuildByOperationID, operationID)
	var i RetrievalIndexBuild
	err := row.Scan(
		&i.ID,
		&i.OperationID,
		&i.ProjectID,
		&i.SourceRevision,
		&i.SourceTree,
		&i.EmbeddingSpaceID,
		&i.PreviousActiveBuildID,
		&i.BuildKind,
		&i.Status,
		&i.ManifestSha256,
		&i.FileCount,
		&i.ChunkCount,
		&i.SymbolCount,
		&i.VectorCount,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getIndexState = `-- name: GetIndexState :one
SELECT project_id, status, active_build_id, active_source_revision,
    active_embedding_space_id, last_build_id, detail, updated_at
FROM retrieval.index_states
WHERE project_id = $1
`

func (q *Queries) GetIndexState(ctx context.Context, projectID pgtype.UUID) (RetrievalIndexState, error) {
	row := q.db.QueryRow(ctx, getIndexState, projectID)
	var i RetrievalIndexState
	err := row.Scan(
		&i.ProjectID,
		&i.Status,
		&i.ActiveBuildID,
		&i.ActiveSourceRevision,
		&i.ActiveEmbeddingSpaceID,
		&i.LastBuildID,
		&i.Detail,
		&i.UpdatedAt,
	)
	return i, err
}

const getIndexStateForUpdate = `-- name: GetIndexStateForUpdate :one
SELECT project_id, status, active_build_id, active_source_revision,
    active_embedding_space_id, last_build_id, detail, updated_at
FROM retrieval.index_states
WHERE project_id = $1
FOR UPDATE
`

func (q *Queries) GetIndexStateForUpdate(ctx context.Context, projectID pgtype.UUID) (RetrievalIndexState, error) {
	row := q.db.QueryRow(ctx, getIndexStateForUpdate, projectID)
	var i RetrievalIndexState
	err := row.Scan(
		&i.ProjectID,
		&i.Status,
		&i.ActiveBuildID,
		&i.ActiveSourceRevision,
		&i.ActiveEmbeddingSpaceID,
		&i.LastBuildID,
		&i.Detail,
		&i.UpdatedAt,
	)
	return i, err
}

const getRetrievalDocument = `-- name: GetRetrievalDocument :one
SELECT id, project_id, file_path, language, created_at
FROM retrieval.documents
WHERE project_id = $1 AND file_path = $2
`

type GetRetrievalDocumentParams struct {
	ProjectID pgtype.UUID
	FilePath  string
}

func (q *Queries) GetRetrievalDocument(ctx context.Context, arg GetRetrievalDocumentParams) (RetrievalDocument, error) {
	row := q.db.QueryRow(ctx, getRetrievalDocument, arg.ProjectID, arg.FilePath)
	var i RetrievalDocument
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.FilePath,
		&i.Language,
		&i.CreatedAt,
	)
	return i, err
}

const initializeIndexState = `-- name: InitializeIndexState :exec
INSERT INTO retrieval.index_states (
    project_id, status, detail, updated_at
) VALUES ($1, 'never_indexed', '', $2)
ON CONFLICT (project_id) DO NOTHING
`

type InitializeIndexStateParams struct {
	ProjectID pgtype.UUID
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InitializeIndexState(ctx context.Context, arg InitializeIndexStateParams) error {
	_, err := q.db.Exec(ctx, initializeIndexState, arg.ProjectID, arg.UpdatedAt)
	return err
}

const insertBuildChunk = `-- name: InsertBuildChunk :exec
INSERT INTO retrieval.index_build_chunks (build_id, chunk_id)
VALUES ($1, $2)
ON CONFLICT (build_id, chunk_id) DO NOTHING
`

type InsertBuildChunkParams struct {
	BuildID pgtype.UUID
	ChunkID pgtype.UUID
}

func (q *Queries) InsertBuildChunk(ctx context.Context, arg InsertBuildChunkParams) error {
	_, err := q.db.Exec(ctx, insertBuildChunk, arg.BuildID, arg.ChunkID)
	return err
}

const insertBuildDocument = `-- name: InsertBuildDocument :exec
INSERT INTO retrieval.index_build_documents (
    build_id, document_version_id, file_path, content_sha256, reused
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (build_id, document_version_id) DO NOTHING
`

type InsertBuildDocumentParams struct {
	BuildID           pgtype.UUID
	DocumentVersionID pgtype.UUID
	FilePath          string
	ContentSha256     string
	Reused            bool
}

func (q *Queries) InsertBuildDocument(ctx context.Context, arg InsertBuildDocumentParams) error {
	_, err := q.db.Exec(ctx, insertBuildDocument,
		arg.BuildID,
		arg.DocumentVersionID,
		arg.FilePath,
		arg.ContentSha256,
		arg.Reused,
	)
	return err
}

const insertBuildSymbol = `-- name: InsertBuildSymbol :exec
INSERT INTO retrieval.index_build_symbols (build_id, symbol_id)
VALUES ($1, $2)
ON CONFLICT (build_id, symbol_id) DO NOTHING
`

type InsertBuildSymbolParams struct {
	BuildID  pgtype.UUID
	SymbolID pgtype.UUID
}

func (q *Queries) InsertBuildSymbol(ctx context.Context, arg InsertBuildSymbolParams) error {
	_, err := q.db.Exec(ctx, insertBuildSymbol, arg.BuildID, arg.SymbolID)
	return err
}

const insertChunkEmbedding = `-- name: InsertChunkEmbedding :exec
INSERT INTO retrieval.chunk_embeddings (
    chunk_id, embedding_space_id, dimensions, embedding,
    embedding_input_sha256, created_at
) VALUES (
    $1, $2, $3, $6::text::vector, $4, $5
) ON CONFLICT (chunk_id, embedding_space_id) DO NOTHING
`

type InsertChunkEmbeddingParams struct {
	ChunkID              pgtype.UUID
	EmbeddingSpaceID     pgtype.UUID
	Dimensions           int32
	EmbeddingInputSha256 string
	CreatedAt            pgtype.Timestamptz
	Embedding            string
}

func (q *Queries) InsertChunkEmbedding(ctx context.Context, arg InsertChunkEmbeddingParams) error {
	_, err := q.db.Exec(ctx, insertChunkEmbedding,
		arg.ChunkID,
		arg.EmbeddingSpaceID,
		arg.Dimensions,
		arg.EmbeddingInputSha256,
		arg.CreatedAt,
		arg.Embedding,
	)
	return err
}

const insertContextItem = `-- name: InsertContextItem :exec
INSERT INTO telemetry.context_items (
    context_package_id, ordinal, candidate_identity, authority_class,
    source_kind, source_identity, source_sha256, source_path, symbol_name,
    start_line, end_line, ranking_signals, included, storage_form,
    inline_content, artifact_id, artifact_sha256, range_start, range_end,
    trajectory_id, trajectory_start, trajectory_end, media_type,
    retrieval_instructions, omission_reason
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
    $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25
)
`

type InsertContextItemParams struct {
	ContextPackageID      pgtype.UUID
	Ordinal               int32
	CandidateIdentity     string
	AuthorityClass        string
	SourceKind            string
	SourceIdentity        string
	SourceSha256          string
	SourcePath            pgtype.Text
	SymbolName            pgtype.Text
	StartLine             pgtype.Int4
	EndLine               pgtype.Int4
	RankingSignals        []byte
	Included              bool
	StorageForm           string
	InlineContent         pgtype.Text
	ArtifactID            pgtype.UUID
	ArtifactSha256        pgtype.Text
	RangeStart            pgtype.Int8
	RangeEnd              pgtype.Int8
	TrajectoryID          pgtype.Text
	TrajectoryStart       pgtype.Int8
	TrajectoryEnd         pgtype.Int8
	MediaType             pgtype.Text
	RetrievalInstructions []byte
	OmissionReason        pgtype.Text
}

func (q *Queries) InsertContextItem(ctx context.Context, arg InsertContextItemParams) error {
	_, err := q.db.Exec(ctx, insertContextItem,
		arg.ContextPackageID,
		arg.Ordinal,
		arg.CandidateIdentity,
		arg.AuthorityClass,
		arg.SourceKind,
		arg.SourceIdentity,
		arg.SourceSha256,
		arg.SourcePath,
		arg.SymbolName,
		arg.StartLine,
		arg.EndLine,
		arg.RankingSignals,
		arg.Included,
		arg.StorageForm,
		arg.InlineContent,
		arg.ArtifactID,
		arg.ArtifactSha256,
		arg.RangeStart,
		arg.RangeEnd,
		arg.TrajectoryID,
		arg.TrajectoryStart,
		arg.TrajectoryEnd,
		arg.MediaType,
		arg.RetrievalInstructions,
		arg.OmissionReason,
	)
	return err
}

const insertContextPackage = `-- name: InsertContextPackage :exec
INSERT INTO telemetry.context_packages (
    id, project_id, task_id, run_id, schema_version, role, source_revision,
    embedding_space_id, byte_budget, token_budget, final_bytes, final_tokens,
    token_estimator, retrieval_configuration, manifest, dossier, dossier_sha256, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18
)
`

type InsertContextPackageParams struct {
	ID                     pgtype.UUID
	ProjectID              pgtype.UUID
	TaskID                 pgtype.UUID
	RunID                  pgtype.UUID
	SchemaVersion          string
	Role                   string
	SourceRevision         string
	EmbeddingSpaceID       pgtype.UUID
	ByteBudget             int32
	TokenBudget            int32
	FinalBytes             int32
	FinalTokens            int32
	TokenEstimator         string
	RetrievalConfiguration []byte
	Manifest               []byte
	Dossier                []byte
	DossierSha256          string
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) InsertContextPackage(ctx context.Context, arg InsertContextPackageParams) error {
	_, err := q.db.Exec(ctx, insertContextPackage,
		arg.ID,
		arg.ProjectID,
		arg.TaskID,
		arg.RunID,
		arg.SchemaVersion,
		arg.Role,
		arg.SourceRevision,
		arg.EmbeddingSpaceID,
		arg.ByteBudget,
		arg.TokenBudget,
		arg.FinalBytes,
		arg.FinalTokens,
		arg.TokenEstimator,
		arg.RetrievalConfiguration,
		arg.Manifest,
		arg.Dossier,
		arg.DossierSha256,
		arg.CreatedAt,
	)
	return err
}

const insertDocumentVersion = `-- name: InsertDocumentVersion :exec
INSERT INTO retrieval.document_versions (
    id, document_id, content_sha256, size_bytes, structural_provenance, created_at
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (document_id, content_sha256) DO NOTHING
`

type InsertDocumentVersionParams struct {
	ID                   pgtype.UUID
	DocumentID           pgtype.UUID
	ContentSha256        string
	SizeBytes            int64
	StructuralProvenance []byte
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) InsertDocumentVersion(ctx context.Context, arg InsertDocumentVersionParams) error {
	_, err := q.db.Exec(ctx, insertDocumentVersion,
		arg.ID,
		arg.DocumentID,
		arg.ContentSha256,
		arg.SizeBytes,
		arg.StructuralProvenance,
		arg.CreatedAt,
	)
	return err
}

const insertEmbeddingSpace = `-- name: InsertEmbeddingSpace :exec
INSERT INTO retrieval.embedding_spaces (
    id, space_sha256, schema_version, model_name, model_revision, dimensions,
    pooling, normalization, quantization, artifact_sha256, license, source_uri,
    serving_image_digest, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) ON CONFLICT (space_sha256) DO NOTHING
`

type InsertEmbeddingSpaceParams struct {
	ID                 pgtype.UUID
	SpaceSha256        string
	SchemaVersion      string
	ModelName          string
	ModelRevision      string
	Dimensions         int32
	Pooling            string
	Normalization      string
	Quantization       string
	ArtifactSha256     string
	License            string
	SourceUri          string
	ServingImageDigest string
	CreatedAt          pgtype.Timestamptz
}

func (q *Queries) InsertEmbeddingSpace(ctx context.Context, arg InsertEmbeddingSpaceParams) error {
	_, err := q.db.Exec(ctx, insertEmbeddingSpace,
		arg.ID,
		arg.SpaceSha256,
		arg.SchemaVersion,
		arg.ModelName,
		arg.ModelRevision,
		arg.Dimensions,
		arg.Pooling,
		arg.Normalization,
		arg.Quantization,
		arg.ArtifactSha256,
		arg.License,
		arg.SourceUri,
		arg.ServingImageDigest,
		arg.CreatedAt,
	)
	return err
}

const insertIndexBuild = `-- name: InsertIndexBuild :exec
INSERT INTO retrieval.index_builds (
    id, operation_id, project_id, source_revision, source_tree,
    embedding_space_id, previous_active_build_id, build_kind, status,
    manifest_sha256, file_count, chunk_count, symbol_count, vector_count,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, 'building', $9, $10, $11, $12, $13, $14
)
`

type InsertIndexBuildParams struct {
	ID                    pgtype.UUID
	OperationID           string
	ProjectID             pgtype.UUID
	SourceRevision        string
	SourceTree            string
	EmbeddingSpaceID      pgtype.UUID
	PreviousActiveBuildID pgtype.UUID
	BuildKind             string
	ManifestSha256        string
	FileCount             int32
	ChunkCount            int32
	SymbolCount           int32
	VectorCount           int32
	CreatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertIndexBuild(ctx context.Context, arg InsertIndexBuildParams) error {
	_, err := q.db.Exec(ctx, insertIndexBuild,
		arg.ID,
		arg.OperationID,
		arg.ProjectID,
		arg.SourceRevision,
		arg.SourceTree,
		arg.EmbeddingSpaceID,
		arg.PreviousActiveBuildID,
		arg.BuildKind,
		arg.ManifestSha256,
		arg.FileCount,
		arg.ChunkCount,
		arg.SymbolCount,
		arg.VectorCount,
		arg.CreatedAt,
	)
	return err
}

const insertRetrievalChunk = `-- name: InsertRetrievalChunk :exec
INSERT INTO retrieval.chunks (
    id, document_version_id, chunk_ordinal, chunk_kind, language, symbol_name,
    signature, start_line, end_line, body, body_sha256,
    structural_provenance, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (id) DO NOTHING
`

type InsertRetrievalChunkParams struct {
	ID                   pgtype.UUID
	DocumentVersionID    pgtype.UUID
	ChunkOrdinal         int32
	ChunkKind            string
	Language             string
	SymbolName           pgtype.Text
	Signature            string
	StartLine            int32
	EndLine              int32
	Body                 string
	BodySha256           string
	StructuralProvenance []byte
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) InsertRetrievalChunk(ctx context.Context, arg InsertRetrievalChunkParams) error {
	_, err := q.db.Exec(ctx, insertRetrievalChunk,
		arg.ID,
		arg.DocumentVersionID,
		arg.ChunkOrdinal,
		arg.ChunkKind,
		arg.Language,
		arg.SymbolName,
		arg.Signature,
		arg.StartLine,
		arg.EndLine,
		arg.Body,
		arg.BodySha256,
		arg.StructuralProvenance,
		arg.CreatedAt,
	)
	return err
}

const insertRetrievalDocument = `-- name: InsertRetrievalDocument :exec
INSERT INTO retrieval.documents (id, project_id, file_path, language, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, file_path) DO NOTHING
`

type InsertRetrievalDocumentParams struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	FilePath  string
	Language  string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertRetrievalDocument(ctx context.Context, arg InsertRetrievalDocumentParams) error {
	_, err := q.db.Exec(ctx, insertRetrievalDocument,
		arg.ID,
		arg.ProjectID,
		arg.FilePath,
		arg.Language,
		arg.CreatedAt,
	)
	return err
}

const insertRetrievalRelation = `-- name: InsertRetrievalRelation :exec
INSERT INTO retrieval.relations (
    id, project_id, build_id, subject_kind, subject_identity, predicate,
    object_kind, object_identity, authority_class, created_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (id) DO NOTHING
`

type InsertRetrievalRelationParams struct {
	ID              pgtype.UUID
	ProjectID       pgtype.UUID
	BuildID         pgtype.UUID
	SubjectKind     string
	SubjectIdentity string
	Predicate       string
	ObjectKind      string
	ObjectIdentity  string
	AuthorityClass  string
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertRetrievalRelation(ctx context.Context, arg InsertRetrievalRelationParams) error {
	_, err := q.db.Exec(ctx, insertRetrievalRelation,
		arg.ID,
		arg.ProjectID,
		arg.BuildID,
		arg.SubjectKind,
		arg.SubjectIdentity,
		arg.Predicate,
		arg.ObjectKind,
		arg.ObjectIdentity,
		arg.AuthorityClass,
		arg.CreatedAt,
	)
	return err
}

const insertRetrievalRelationSource = `-- name: InsertRetrievalRelationSource :exec
INSERT INTO retrieval.relation_sources (
    relation_id, source_kind, source_identity, source_sha256, artifact_id, provenance
) VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (relation_id, source_kind, source_identity) DO NOTHING
`

type InsertRetrievalRelationSourceParams struct {
	RelationID     pgtype.UUID
	SourceKind     string
	SourceIdentity string
	SourceSha256   string
	ArtifactID     pgtype.UUID
	Provenance     []byte
}

func (q *Queries) InsertRetrievalRelationSource(ctx context.Context, arg InsertRetrievalRelationSourceParams) error {
	_, err := q.db.Exec(ctx, insertRetrievalRelationSource,
		arg.RelationID,
		arg.SourceKind,
		arg.SourceIdentity,
		arg.SourceSha256,
		arg.ArtifactID,
		arg.Provenance,
	)
	return err
}

const insertRetrievalSymbol = `-- name: InsertRetrievalSymbol :exec
INSERT INTO retrieval.symbols (
    id, document_version_id, chunk_id, symbol_name, symbol_kind, signature,
    start_line, end_line, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO NOTHING
`

type InsertRetrievalSymbolParams struct {
	ID                pgtype.UUID
	DocumentVersionID pgtype.UUID
	ChunkID           pgtype.UUID
	SymbolName        string
	SymbolKind        string
	Signature         string
	StartLine         int32
	EndLine           int32
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertRetrievalSymbol(ctx context.Context, arg InsertRetrievalSymbolParams) error {
	_, err := q.db.Exec(ctx, insertRetrievalSymbol,
		arg.ID,
		arg.DocumentVersionID,
		arg.ChunkID,
		arg.SymbolName,
		arg.SymbolKind,
		arg.Signature,
		arg.StartLine,
		arg.EndLine,
		arg.CreatedAt,
	)
	return err
}

const insertSymbolEdge = `-- name: InsertSymbolEdge :exec
INSERT INTO retrieval.symbol_edges (
    id, document_version_id, from_symbol_id, edge_kind, target_symbol,
    target_path, source_line, provenance, created_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO NOTHING
`

type InsertSymbolEdgeParams struct {
	ID                pgtype.UUID
	DocumentVersionID pgtype.UUID
	FromSymbolID      pgtype.UUID
	EdgeKind          string
	TargetSymbol      string
	TargetPath        pgtype.Text
	SourceLine        int32
	Provenance        []byte
	CreatedAt         pgtype.Timestamptz
}

func (q *Queries) InsertSymbolEdge(ctx context.Context, arg InsertSymbolEdgeParams) error {
	_, err := q.db.Exec(ctx, insertSymbolEdge,
		arg.ID,
		arg.DocumentVersionID,
		arg.FromSymbolID,
		arg.EdgeKind,
		arg.TargetSymbol,
		arg.TargetPath,
		arg.SourceLine,
		arg.Provenance,
		arg.CreatedAt,
	)
	return err
}

const listActiveChunkEmbeddingIdentities = `-- name: ListActiveChunkEmbeddingIdentities :many
SELECT ce.chunk_id, ce.embedding_space_id, ce.dimensions,
    ce.embedding_input_sha256, ce.embedding::text AS embedding_text
FROM retrieval.index_states AS ist
JOIN retrieval.index_builds AS ib ON ib.id = ist.active_build_id
JOIN retrieval.index_build_chunks AS ibc ON ibc.build_id = ib.id
JOIN retrieval.chunk_embeddings AS ce ON ce.chunk_id = ibc.chunk_id
    AND ce.embedding_space_id = ib.embedding_space_id
WHERE ist.project_id = $1
ORDER BY ce.chunk_id
`

type ListActiveChunkEmbeddingIdentitiesRow struct {
	ChunkID              pgtype.UUID
	EmbeddingSpaceID     pgtype.UUID
	Dimensions           int32
	EmbeddingInputSha256 string
	EmbeddingText        string
}

func (q *Queries) ListActiveChunkEmbeddingIdentities(ctx context.Context, projectID pgtype.UUID) ([]ListActiveChunkEmbeddingIdentitiesRow, error) {
	rows, err := q.db.Query(ctx, listActiveChunkEmbeddingIdentities, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveChunkEmbeddingIdentitiesRow
	for rows.Next() {
		var i ListActiveChunkEmbeddingIdentitiesRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.EmbeddingSpaceID,
			&i.Dimensions,
			&i.EmbeddingInputSha256,
			&i.EmbeddingText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveDocuments = `-- name: ListActiveDocuments :many
SELECT d.id AS document_id, dv.id AS document_version_id, d.file_path,
    d.language, dv.content_sha256, dv.size_bytes, dv.structural_provenance
FROM retrieval.index_states AS ist
JOIN retrieval.index_build_documents AS ibd ON ibd.build_id = ist.active_build_id
JOIN retrieval.document_versions AS dv ON dv.id = ibd.document_version_id
JOIN retrieval.documents AS d ON d.id = dv.document_id
WHERE ist.project_id = $1
ORDER BY d.file_path
`

type ListActiveDocumentsRow struct {
	DocumentID           pgtype.UUID
	DocumentVersionID    pgtype.UUID
	FilePath             string
	Language             string
	ContentSha256        string
	SizeBytes            int64
	StructuralProvenance []byte
}

func (q *Queries) ListActiveDocuments(ctx context.Context, projectID pgtype.UUID) ([]ListActiveDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listActiveDocuments, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveDocumentsRow
	for rows.Next() {
		var i ListActiveDocumentsRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.DocumentVersionID,
			&i.FilePath,
			&i.Language,
			&i.ContentSha256,
			&i.SizeBytes,
			&i.StructuralProvenance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRetrievalRelations = `-- name: ListActiveRetrievalRelations :many
SELECT r.id, r.project_id, r.build_id, r.subject_kind, r.subject_identity,
    r.predicate, r.object_kind, r.object_identity, r.authority_class,
    r.created_at
FROM retrieval.index_states AS ist
JOIN retrieval.relations AS r ON r.build_id = ist.active_build_id
WHERE ist.project_id = $1
ORDER BY r.subject_kind, r.subject_identity, r.predicate,
    r.object_kind, r.object_identity, r.id
LIMIT $2
`

type ListActiveRetrievalRelationsParams struct {
	ProjectID pgtype.UUID
	Limit     int32
}

func (q *Queries) ListActiveRetrievalRelations(ctx context.Context, arg ListActiveRetrievalRelationsParams) ([]RetrievalRelation, error) {
	rows, err := q.db.Query(ctx, listActiveRetrievalRelations, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievalRelation
	for rows.Next() {
		var i RetrievalRelation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.BuildID,
			&i.SubjectKind,
			&i.SubjectIdentity,
			&i.Predicate,
			&i.ObjectKind,
			&i.ObjectIdentity,
			&i.AuthorityClass,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContextItems = `-- name: ListContextItems :many
SELECT context_package_id, ordinal, candidate_identity, authority_class,
    source_kind, source_identity, source_sha256, source_path, symbol_name,
    start_line, end_line, ranking_signals, included, storage_form,
    inline_content, artifact_id, artifact_sha256, range_start, range_end,
    trajectory_id, trajectory_start, trajectory_end, media_type,
    retrieval_instructions, omission_reason
FROM telemetry.context_items
WHERE context_package_id = $1 AND included
ORDER BY ordinal
LIMIT $2
`

type ListContextItemsParams struct {
	ContextPackageID pgtype.UUID
	Limit            int32
}

func (q *Queries) ListContextItems(ctx context.Context, arg ListContextItemsParams) ([]TelemetryContextItem, error) {
	rows, err := q.db.Query(ctx, listContextItems, arg.ContextPackageID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TelemetryContextItem
	for rows.Next() {
		var i TelemetryContextItem
		if err := rows.Scan(
			&i.ContextPackageID,
			&i.Ordinal,
			&i.CandidateIdentity,
			&i.AuthorityClass,
			&i.SourceKind,
			&i.SourceIdentity,
			&i.SourceSha256,
			&i.SourcePath,
			&i.SymbolName,
			&i.StartLine,
			&i.EndLine,
			&i.RankingSignals,
			&i.Included,
			&i.StorageForm,
			&i.InlineContent,
			&i.ArtifactID,
			&i.ArtifactSha256,
			&i.RangeStart,
			&i.RangeEnd,
			&i.TrajectoryID,
			&i.TrajectoryStart,
			&i.TrajectoryEnd,
			&i.MediaType,
			&i.RetrievalInstructions,
			&i.OmissionReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentChunks = `-- name: ListDocumentChunks :many
SELECT id, document_version_id, chunk_ordinal, chunk_kind, language,
    symbol_name, signature, start_line, end_line, body, body_sha256,
    structural_provenance, created_at
FROM retrieval.chunks
WHERE document_version_id = $1
ORDER BY chunk_ordinal
`

type ListDocumentChunksRow struct {
	ID                   pgtype.UUID
	DocumentVersionID    pgtype.UUID
	ChunkOrdinal         int32
	ChunkKind            string
	Language             string
	SymbolName           pgtype.Text
	Signature            string
	StartLine            int32
	EndLine              int32
	Body                 string
	BodySha256           string
	StructuralProvenance []byte
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) ListDocumentChunks(ctx context.Context, documentVersionID pgtype.UUID) ([]ListDocumentChunksRow, error) {
	rows, err := q.db.Query(ctx, listDocumentChunks, documentVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentChunksRow
	for rows.Next() {
		var i ListDocumentChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.DocumentVersionID,
			&i.ChunkOrdinal,
			&i.ChunkKind,
			&i.Language,
			&i.SymbolName,
			&i.Signature,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.BodySha256,
			&i.StructuralProvenance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentEdges = `-- name: ListDocumentEdges :many
SELECT id, document_version_id, from_symbol_id, edge_kind, target_symbol,
    target_path, source_line, provenance, created_at
FROM retrieval.symbol_edges
WHERE document_version_id = $1
ORDER BY source_line, edge_kind, target_symbol, id
`

func (q *Queries) ListDocumentEdges(ctx context.Context, documentVersionID pgtype.UUID) ([]RetrievalSymbolEdge, error) {
	rows, err := q.db.Query(ctx, listDocumentEdges, documentVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievalSymbolEdge
	for rows.Next() {
		var i RetrievalSymbolEdge
		if err := rows.Scan(
			&i.ID,
			&i.DocumentVersionID,
			&i.FromSymbolID,
			&i.EdgeKind,
			&i.TargetSymbol,
			&i.TargetPath,
			&i.SourceLine,
			&i.Provenance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentSymbols = `-- name: ListDocumentSymbols :many
SELECT id, document_version_id, chunk_id, symbol_name, symbol_kind, signature,
    start_line, end_line, created_at
FROM retrieval.symbols
WHERE document_version_id = $1
ORDER BY start_line, symbol_name
`

func (q *Queries) ListDocumentSymbols(ctx context.Context, documentVersionID pgtype.UUID) ([]RetrievalSymbol, error) {
	rows, err := q.db.Query(ctx, listDocumentSymbols, documentVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievalSymbol
	for rows.Next() {
		var i RetrievalSymbol
		if err := rows.Scan(
			&i.ID,
			&i.DocumentVersionID,
			&i.ChunkID,
			&i.SymbolName,
			&i.SymbolKind,
			&i.Signature,
			&i.StartLine,
			&i.EndLine,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRetrievalRelationSources = `-- name: ListRetrievalRelationSources :many
SELECT relation_id, source_kind, source_identity, source_sha256, artifact_id,
    provenance
FROM retrieval.relation_sources
WHERE relation_id = $1
ORDER BY source_kind, source_identity
`

func (q *Queries) ListRetrievalRelationSources(ctx context.Context, relationID pgtype.UUID) ([]RetrievalRelationSource, error) {
	rows, err := q.db.Query(ctx, listRetrievalRelationSources, relationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetrievalRelationSource
	for rows.Next() {
		var i RetrievalRelationSource
		if err := rows.Scan(
			&i.RelationID,
			&i.SourceKind,
			&i.SourceIdentity,
			&i.SourceSha256,
			&i.ArtifactID,
			&i.Provenance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markIndexDirty = `-- name: MarkIndexDirty :exec
UPDATE retrieval.index_states
SET status = 'dirty', detail = $2, updated_at = $3
WHERE project_id = $1
`

type MarkIndexDirtyParams struct {
	ProjectID pgtype.UUID
	Detail    string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) MarkIndexDirty(ctx context.Context, arg MarkIndexDirtyParams) error {
	_, err := q.db.Exec(ctx, markIndexDirty, arg.ProjectID, arg.Detail, arg.UpdatedAt)
	return err
}

const setIndexBuilding = `-- name: SetIndexBuilding :exec
UPDATE retrieval.index_states
SET status = 'building', last_build_id = $2, detail = '', updated_at = $3
WHERE project_id = $1
`

type SetIndexBuildingParams struct {
	ProjectID   pgtype.UUID
	LastBuildID pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) SetIndexBuilding(ctx context.Context, arg SetIndexBuildingParams) error {
	_, err := q.db.Exec(ctx, setIndexBuilding, arg.ProjectID, arg.LastBuildID, arg.UpdatedAt)
	return err
}

const setIndexFailed = `-- name: SetIndexFailed :exec
UPDATE retrieval.index_states
SET status = CASE WHEN active_build_id IS NULL THEN 'failed' ELSE 'clean' END,
    last_build_id = $2, detail = $3, updated_at = $4
WHERE project_id = $1
`

type SetIndexFailedParams struct {
	ProjectID   pgtype.UUID
	LastBuildID pgtype.UUID
	Detail      string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) SetIndexFailed(ctx context.Context, arg SetIndexFailedParams) error {
	_, err := q.db.Exec(ctx, setIndexFailed,
		arg.ProjectID,
		arg.LastBuildID,
		arg.Detail,
		arg.UpdatedAt,
	)
	return err
}

const structuralChunks = `-- name: StructuralChunks :many
SELECT DISTINCT c.id AS chunk_id, d.file_path, c.language, c.symbol_name,
    c.signature, c.chunk_kind, c.start_line, c.end_line, c.body,
    c.body_sha256, ib.source_revision
FROM retrieval.index_states AS ist
JOIN retrieval.index_builds AS ib ON ib.id = ist.active_build_id
JOIN retrieval.index_build_symbols AS ibs ON ibs.build_id = ib.id
JOIN retrieval.symbols AS s ON s.id = ibs.symbol_id
JOIN retrieval.chunks AS c ON c.id = s.chunk_id
JOIN retrieval.document_versions AS dv ON dv.id = c.document_version_id
JOIN retrieval.documents AS d ON d.id = dv.document_id
WHERE ist.project_id = $1
  AND (
    lower(s.symbol_name) = ANY($2::text[])
    OR EXISTS (
      SELECT 1
      FROM retrieval.index_build_symbols AS seed_ibs
      JOIN retrieval.symbols AS seed ON seed.id = seed_ibs.symbol_id
      JOIN retrieval.symbol_edges AS se ON se.document_version_id IN (s.document_version_id, seed.document_version_id)
      WHERE seed_ibs.build_id = ib.id
        AND lower(seed.symbol_name) = ANY($2::text[])
        AND (
          (se.from_symbol_id = seed.id AND lower(se.target_symbol) = lower(s.symbol_name))
          OR (se.from_symbol_id = s.id AND lower(se.target_symbol) = lower(seed.symbol_name))
        )
    )
  )
ORDER BY d.file_path, c.start_line, c.id
LIMIT $3
`

type StructuralChunksParams struct {
	ProjectID   pgtype.UUID
	SymbolNames []string
	ResultLimit int32
}

type StructuralChunksRow struct {
	ChunkID        pgtype.UUID
	FilePath       string
	Language       string
	SymbolName     pgtype.Text
	Signature      string
	ChunkKind      string
	StartLine      int32
	EndLine        int32
	Body           string
	BodySha256     string
	SourceRevision string
}

func (q *Queries) StructuralChunks(ctx context.Context, arg StructuralChunksParams) ([]StructuralChunksRow, error) {
	rows, err := q.db.Query(ctx, structuralChunks, arg.ProjectID, arg.SymbolNames, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StructuralChunksRow
	for rows.Next() {
		var i StructuralChunksRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.FilePath,
			&i.Language,
			&i.SymbolName,
			&i.Signature,
			&i.ChunkKind,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.BodySha256,
			&i.SourceRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vectorChunks1024 = `-- name: VectorChunks1024 :many
SELECT c.id AS chunk_id, d.file_path, c.language, c.symbol_name, c.signature,
    c.chunk_kind, c.start_line, c.end_line, c.body, c.body_sha256,
    ib.source_revision,
    (1 - (ce.embedding::halfvec(1024) <=> $1::text::halfvec(1024)))::double precision AS vector_score
FROM retrieval.index_states AS ist
JOIN retrieval.index_builds AS ib ON ib.id = ist.active_build_id
JOIN retrieval.index_build_chunks AS ibc ON ibc.build_id = ib.id
JOIN retrieval.chunks AS c ON c.id = ibc.chunk_id
JOIN retrieval.chunk_embeddings AS ce ON ce.chunk_id = c.id AND ce.embedding_space_id = ib.embedding_space_id
JOIN retrieval.document_versions AS dv ON dv.id = c.document_version_id
JOIN retrieval.documents AS d ON d.id = dv.document_id
WHERE ist.project_id = $2 AND ce.dimensions = 1024
ORDER BY ce.embedding::halfvec(1024) <=> $1::text::halfvec(1024), d.file_path, c.start_line, c.id
LIMIT $3
`

type VectorChunks1024Params struct {
	QueryVector string
	ProjectID   pgtype.UUID
	ResultLimit int32
}

type VectorChunks1024Row struct {
	ChunkID        pgtype.UUID
	FilePath       string
	Language       string
	SymbolName     pgtype.Text
	Signature      string
	ChunkKind      string
	StartLine      int32
	EndLine        int32
	Body           string
	BodySha256     string
	SourceRevision string
	VectorScore    float64
}

func (q *Queries) VectorChunks1024(ctx context.Context, arg VectorChunks1024Params) ([]VectorChunks1024Row, error) {
	rows, err := q.db.Query(ctx, vectorChunks1024, arg.QueryVector, arg.ProjectID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VectorChunks1024Row
	for rows.Next() {
		var i VectorChunks1024Row
		if err := rows.Scan(
			&i.ChunkID,
			&i.FilePath,
			&i.Language,
			&i.SymbolName,
			&i.Signature,
			&i.ChunkKind,
			&i.StartLine,
			&i.EndLine,
			&i.Body,
			&i.BodySha256,
			&i.SourceRevision,
			&i.VectorScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
