#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"

TMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/revolvr-run-once-smoke.XXXXXX")"
cleanup() {
  rm -rf "$TMP_ROOT"
}
trap cleanup EXIT

BIN="$TMP_ROOT/revolvr"
WORK_DIR="$TMP_ROOT/work"
FAKE_CODEX="$TMP_ROOT/fake-codex"
TASK_REL=".agent/tasks/001-fake-codex-smoke.md"
TASK_FILE="$WORK_DIR/$TASK_REL"

assert_contains() {
  local file="$1"
  local expected="$2"
  if ! grep -Fq "$expected" "$file"; then
    echo "Expected $file to contain:" >&2
    echo "  $expected" >&2
    echo "Actual output:" >&2
    sed 's/^/  /' "$file" >&2
    exit 1
  fi
}

assert_file_exists() {
  local path="$1"
  if [[ ! -f "$path" ]]; then
    echo "Expected file to exist: $path" >&2
    exit 1
  fi
}

assert_nonempty() {
  local name="$1"
  local value="$2"
  if [[ -z "$value" ]]; then
    echo "Expected non-empty $name" >&2
    exit 1
  fi
}

run_revolvr() {
  local output_name="$1"
  shift
  echo "Running: revolvr $*"
  if ! (cd "$WORK_DIR" && "$BIN" "$@") >"$TMP_ROOT/$output_name.out" 2>"$TMP_ROOT/$output_name.err"; then
    echo "revolvr $* failed" >&2
    echo "stdout:" >&2
    sed 's/^/  /' "$TMP_ROOT/$output_name.out" >&2
    echo "stderr:" >&2
    sed 's/^/  /' "$TMP_ROOT/$output_name.err" >&2
    exit 1
  fi
}

write_fake_codex() {
  cat >"$FAKE_CODEX" <<'FAKE_CODEX_SH'
#!/usr/bin/env bash
set -euo pipefail

fail() {
  echo "fake codex: $*" >&2
  exit 64
}

if [[ "$#" -eq 0 ]]; then
  fail "missing subcommand"
fi
if [[ "$1" != "exec" ]]; then
  fail "expected first argument to be exec, got $1"
fi
shift

json_seen=0
dangerous_seen=0
cd_dir=""
last_message=""
stdin_marker=0

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --json)
      json_seen=1
      shift
      ;;
    --dangerously-bypass-approvals-and-sandbox)
      dangerous_seen=1
      shift
      ;;
    --yolo)
      fail "unexpected --yolo alias; expected --dangerously-bypass-approvals-and-sandbox"
      ;;
    --sandbox|--ask-for-approval|--approval-policy)
      fail "unexpected flag while dangerous bypass is expected: $1"
      ;;
    --cd)
      [[ "$#" -ge 2 ]] || fail "--cd requires a value"
      cd_dir="$2"
      shift 2
      ;;
    --output-last-message)
      [[ "$#" -ge 2 ]] || fail "--output-last-message requires a value"
      last_message="$2"
      shift 2
      ;;
    -)
      stdin_marker=1
      shift
      ;;
    *)
      fail "unexpected argument: $1"
      ;;
  esac
done

[[ "$json_seen" -eq 1 ]] || fail "missing --json"
[[ "$dangerous_seen" -eq 1 ]] || fail "missing dangerous bypass flag"
[[ "$stdin_marker" -eq 1 ]] || fail "missing stdin prompt marker '-'"
[[ -n "$cd_dir" ]] || fail "missing --cd"
[[ -d "$cd_dir" ]] || fail "--cd does not point at a directory: $cd_dir"
[[ "$(cd "$cd_dir" && pwd -P)" == "$(pwd -P)" ]] || fail "--cd does not match working directory"
[[ -n "$last_message" ]] || fail "missing --output-last-message"

prompt="$(cat)"
[[ -n "$prompt" ]] || fail "missing prompt on stdin"
grep -Fq "# Revolvr Codex Pass" <<<"$prompt" || fail "prompt missing revolvr header"
grep -Fq "Run once success path through strict fake Codex" <<<"$prompt" || fail "prompt missing selected task"

run_id="$(sed -n 's/^- Run ID: `\([^`]*\)`$/\1/p' <<<"$prompt" | head -n 1)"
pass_id="$(sed -n 's/^- Pass ID: `\([^`]*\)`$/\1/p' <<<"$prompt" | head -n 1)"
task_id="$(sed -n 's/^- Task ID: `\([^`]*\)`$/\1/p' <<<"$prompt" | head -n 1)"
receipt_path="$(sed -n 's/^- Receipt path: `\([^`]*\)`$/\1/p' <<<"$prompt" | head -n 1)"
task_text="$(awk '/^```text$/ { getline; print; exit }' <<<"$prompt")"

[[ -n "$run_id" ]] || fail "could not extract run id"
[[ -n "$pass_id" ]] || fail "could not extract pass id"
[[ -n "$task_id" ]] || fail "could not extract task id"
[[ -n "$receipt_path" ]] || fail "could not extract receipt path"
[[ -n "$task_text" ]] || fail "could not extract task text"
[[ "$run_id" == "$pass_id" ]] || fail "run id and pass id differ"

printf 'generated by fake codex\n' >generated.txt
mkdir -p "$(dirname "$receipt_path")"
cat >"$receipt_path" <<RECEIPT
---
schema_version: revolvr.receipt.v1
run_id: "$run_id"
pass_id: "$pass_id"
task_id: "$task_id"
task: "$task_text"
verdict: completed
timestamp: 2026-07-07T00:00:00Z
codex_exit_code: 0
verification_status: passed
commit_sha: ""
changed_files:
  - generated.txt
verification:
  - command: 'sh -c "test -f generated.txt"'
    exit_code: 0
    status: passed
metrics:
  input_tokens: 0
  output_tokens: 0
  duration_seconds: 0
---
## Summary

Fake Codex created generated.txt.

## Changed Files

- generated.txt

## Verification

- sh -c "test -f generated.txt" (exit_code=0, status=passed)

## Concerns

None.

## Next Steps

None.
RECEIPT

printf 'fake codex completed\n' >"$last_message"
printf '%s\n' '{"type":"turn.completed","final_message":"fake codex completed","usage":{"input_tokens":11,"output_tokens":5,"duration_seconds":1}}'
FAKE_CODEX_SH
  chmod +x "$FAKE_CODEX"
}

echo "Building revolvr smoke-test binary..."
go build -o "$BIN" ./cmd/revolvr

write_fake_codex

mkdir -p "$WORK_DIR"
git -C "$WORK_DIR" init -q
git -C "$WORK_DIR" config user.name "Revolvr Smoke"
git -C "$WORK_DIR" config user.email "revolvr-smoke@example.invalid"
printf '# Smoke workspace\n' >"$WORK_DIR/README.md"
git -C "$WORK_DIR" add README.md
git -C "$WORK_DIR" commit -q -m "Initial smoke workspace"

run_revolvr init init
assert_contains "$TMP_ROOT/init.out" "Initialized revolvr state:"
assert_contains "$WORK_DIR/.git/info/exclude" "/.revolvr/"
assert_file_exists "$WORK_DIR/.agent/profiles/implementer.md"
assert_file_exists "$WORK_DIR/.agent/profiles/auditor.md"
assert_file_exists "$WORK_DIR/.agent/profiles/documentor.md"
assert_contains "$WORK_DIR/.agent/profiles/implementer.md" "You are the implementer for this Revolvr pass."
mkdir -p "$(dirname "$TASK_FILE")"
cat >"$TASK_FILE" <<'TASK_MD'
---
id: smoke-fake-codex
status: pending
priority: 10
---
# Fake Codex run smoke

Run once success path through strict fake Codex
TASK_MD
TASK_SHA="$(sha256sum "$TASK_FILE" | awk '{print $1}')"
TASK_BYTES="$(wc -c <"$TASK_FILE" | tr -d ' ')"
git -C "$WORK_DIR" add .agent/profiles "$TASK_REL"
git -C "$WORK_DIR" commit -q -m "Add revolvr profiles and smoke task"
git -C "$WORK_DIR" status --short >"$TMP_ROOT/post-init-git-status.out"
if [[ -s "$TMP_ROOT/post-init-git-status.out" ]]; then
  echo "Expected committed revolvr profiles and task to leave Git status clean" >&2
  sed 's/^/  /' "$TMP_ROOT/post-init-git-status.out" >&2
  exit 1
fi

cat >"$WORK_DIR/.revolvr/config.yaml" <<CONFIG_YAML
codex:
  executable: $FAKE_CODEX
  timeout_seconds: 30
verification:
  missing_policy: fail
  commands:
    - name: sh
      args:
        - -c
        - test -f generated.txt
      timeout_seconds: 30
CONFIG_YAML

run_revolvr config-check config check
assert_contains "$TMP_ROOT/config-check.out" "Config found: true"
assert_contains "$TMP_ROOT/config-check.out" "Codex executable: $FAKE_CODEX"
assert_contains "$TMP_ROOT/config-check.out" "Codex dangerously bypass approvals and sandbox: true"
assert_contains "$TMP_ROOT/config-check.out" "Verification command count: 1"
assert_contains "$TMP_ROOT/config-check.out" 'Verification command 0: name=sh args=["-c", "test -f generated.txt"] timeout=30s'

run_revolvr run-once run --once
assert_contains "$TMP_ROOT/run-once.out" "Run "
assert_contains "$TMP_ROOT/run-once.out" " completed task "
assert_contains "$TMP_ROOT/run-once.out" "; commit "

RUN_ID="$(awk '/^Run / {print $2; exit}' "$TMP_ROOT/run-once.out")"
assert_nonempty "run id" "$RUN_ID"

assert_file_exists "$WORK_DIR/generated.txt"
assert_contains "$WORK_DIR/generated.txt" "generated by fake codex"
assert_contains "$TASK_FILE" "status: completed"

run_revolvr status status
assert_contains "$TMP_ROOT/status.out" "Recent runs: 1"
assert_contains "$TMP_ROOT/status.out" "Latest run: $RUN_ID (completed)"

if [[ "$(git -C "$WORK_DIR" rev-list --count HEAD)" != "3" ]]; then
  echo "Expected fake-Codex run to create exactly one commit after the profile commit" >&2
  git -C "$WORK_DIR" log --oneline >&2
  exit 1
fi
git -C "$WORK_DIR" show --name-only --format=%s HEAD >"$TMP_ROOT/git-show.out"
assert_contains "$TMP_ROOT/git-show.out" "Fake Codex run smoke"
assert_contains "$TMP_ROOT/git-show.out" "generated.txt"
assert_contains "$TMP_ROOT/git-show.out" "$TASK_REL"
git -C "$WORK_DIR" status --short --untracked-files=all >"$TMP_ROOT/post-run-git-status.out"
if [[ -s "$TMP_ROOT/post-run-git-status.out" ]]; then
  echo "Expected successful run commit to leave Git status clean" >&2
  sed 's/^/  /' "$TMP_ROOT/post-run-git-status.out" >&2
  exit 1
fi

assert_file_exists "$WORK_DIR/.revolvr/runs/$RUN_ID/context.md"
assert_file_exists "$WORK_DIR/.revolvr/runs/$RUN_ID/context.json"
assert_file_exists "$WORK_DIR/.revolvr/runs/$RUN_ID/codex.jsonl"
assert_file_exists "$WORK_DIR/.revolvr/runs/$RUN_ID/codex.stderr"
assert_file_exists "$WORK_DIR/.revolvr/runs/$RUN_ID/last-message.txt"
assert_file_exists "$WORK_DIR/.revolvr/receipts/$RUN_ID.md"
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.md" "## Run Profile"
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.md" "## Selected Task"
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.md" "## Required Receipt Schema"
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.json" '"context_payload_path"'
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.json" '"context_payload_sha256"'
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.json" '"label": "selected_task"'
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.json" "\"path\": \"$TASK_REL\""
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.json" "\"sha256\": \"$TASK_SHA\""
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.json" "\"byte_size\": $TASK_BYTES"
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.json" '"label": "run_profile"'
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/context.json" '"path": ".agent/profiles/implementer.md"'
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/codex.jsonl" '"type":"turn.completed"'
assert_contains "$WORK_DIR/.revolvr/runs/$RUN_ID/last-message.txt" "fake codex completed"
assert_contains "$WORK_DIR/.revolvr/receipts/$RUN_ID.md" "verdict: completed"
assert_contains "$WORK_DIR/.revolvr/receipts/$RUN_ID.md" "verification_status: passed"
assert_contains "$WORK_DIR/.revolvr/receipts/$RUN_ID.md" "generated.txt"
assert_contains "$WORK_DIR/.revolvr/receipts/$RUN_ID.md" "$TASK_REL"

run_revolvr show-run show "$RUN_ID"
assert_contains "$TMP_ROOT/show-run.out" "Run ID: $RUN_ID"
assert_contains "$TMP_ROOT/show-run.out" "Status: completed"
assert_contains "$TMP_ROOT/show-run.out" "Codex exit code: 0"
assert_contains "$TMP_ROOT/show-run.out" "Verification status: passed"
assert_contains "$TMP_ROOT/show-run.out" "Artifacts:"
assert_contains "$TMP_ROOT/show-run.out" "context payload: .revolvr/runs/$RUN_ID/context.md"
assert_contains "$TMP_ROOT/show-run.out" "context manifest: .revolvr/runs/$RUN_ID/context.json"
assert_contains "$TMP_ROOT/show-run.out" "codex stdout jsonl: .revolvr/runs/$RUN_ID/codex.jsonl"
assert_contains "$TMP_ROOT/show-run.out" "receipt: .revolvr/receipts/$RUN_ID.md"
assert_contains "$TMP_ROOT/show-run.out" "Diagnostics:"
assert_contains "$TMP_ROOT/show-run.out" "outcome: committed"
assert_contains "$TMP_ROOT/show-run.out" "codex: exit_code=0, timed_out=false"
assert_contains "$TMP_ROOT/show-run.out" "verification: passed"
assert_contains "$TMP_ROOT/show-run.out" "commit: "
assert_contains "$TMP_ROOT/show-run.out" "receipt: completed (.revolvr/receipts/$RUN_ID.md)"
assert_contains "$TMP_ROOT/show-run.out" "changed files:"
assert_contains "$TMP_ROOT/show-run.out" "generated.txt"
assert_contains "$TMP_ROOT/show-run.out" "$TASK_REL"
assert_contains "$TMP_ROOT/show-run.out" "Events:"

echo "Fake-Codex run --once smoke test passed."
